/* 
 * 
 * Confidential Information of Telekinesys Research Limited (t/a Havok).  Not for disclosure or distribution without Havok's
 * prior written consent.This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Level 2 and Level 3 source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2007 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 * 
 */

// Autogenerated by genRegister.py

HK_STRUCT(hkxAnimatedFloat)
HK_STRUCT(hkxAnimatedMatrix)
HK_STRUCT(hkxAnimatedQuaternion)
HK_STRUCT(hkxAnimatedVector)
HK_STRUCT(hkxAttribute)
HK_STRUCT(hkxAttributeGroup)
HK_STRUCT(hkxAttributeHolder)
HK_STRUCT(hkxCamera)
HK_STRUCT(hkxEdgeSelectionChannel)
HK_STRUCT(hkxEnvironment)
HK_STRUCT(hkxEnvironmentVariable)
HK_STRUCT(hkxIndexBuffer)
HK_STRUCT(hkxLight)
HK_STRUCT(hkxMaterial)
HK_STRUCT(hkxMaterialEffect)
HK_STRUCT(hkxMaterialTextureStage)
HK_STRUCT(hkxMesh)
HK_STRUCT(hkxMeshSection)
HK_STRUCT(hkxMeshUserChannelInfo)
HK_STRUCT(hkxNode)
HK_STRUCT(hkxNodeAnnotationData)
HK_STRUCT(hkxNodeSelectionSet)
HK_STRUCT(hkxScene)
HK_STRUCT(hkxSkinBinding)
HK_STRUCT(hkxSparselyAnimatedBool)
HK_STRUCT(hkxSparselyAnimatedEnum)
HK_STRUCT(hkxSparselyAnimatedInt)
HK_STRUCT(hkxSparselyAnimatedString)
HK_STRUCT(hkxSparselyAnimatedStringStringType)
HK_STRUCT(hkxTextureFile)
HK_STRUCT(hkxTextureInplace)
HK_STRUCT(hkxTriangleSelectionChannel)
HK_STRUCT(hkxVertexBuffer)
HK_STRUCT(hkxVertexFloatDataChannel)
HK_STRUCT(hkxVertexFormat)
HK_STRUCT(hkxVertexIntDataChannel)
HK_STRUCT(hkxVertexP4N4C1T2)
HK_STRUCT(hkxVertexP4N4T4B4C1T2)
HK_STRUCT(hkxVertexP4N4T4B4W4I4C1Q2)
HK_STRUCT(hkxVertexP4N4T4B4W4I4Q4)
HK_STRUCT(hkxVertexP4N4W4I4C1Q2)
HK_STRUCT(hkxVertexSelectionChannel)
HK_STRUCT(hkxVertexVectorDataChannel)

/*
* Havok SDK - PUBLIC RELEASE, BUILD(#20070919)
*
* Confidential Information of Havok.  (C) Copyright 1999-2007 
* Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
* Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
* rights, and intellectual property rights in the Havok software remain in
* Havok and/or its suppliers.
*
* Use of this software for evaluation purposes is subject to and indicates 
* acceptance of the End User licence Agreement for this product. A copy of 
* the license is included with this software and is also available from salesteam@havok.com.
*
*/
