#if 0
//
// Generated by 2.0.7776.0
//
//   fxc /T ps_1_1 /E PS_AcCxformGauraud scaleform.hlsl /Fh
//    PS_AcCxformGauraud.hlsl.h
//
//
// Parameters:
//
//   float4 cxadd;
//   float4 cxmul;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   cxmul        c2       1
//   cxadd        c3       1
//

// Shader type: pixel 

xps_3_0
defconst cxadd, float, vector, [1, 4], c3
defconst cxmul, float, vector, [1, 4], c2
config AutoSerialize=false
config AutoResource=false
config PsMaxReg=1
// PsExportColorCount=1

dcl_color_centroid r0
dcl_color1_centroid r1


    alloc colors
    exece
    mad r0, r0, c2, c3
    mul r0.w, r0.w, r1.w
    mul r0.xyz, r0.w, r0.xyz
    mov oC0, r0

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xps_PS_AcCxformGauraud[] =
{
    0x102a1100, 0x000000c4, 0x00000048, 0x00000000, 0x00000024, 0x00000000, 
    0x0000009c, 0x00000000, 0x00000000, 0x00000074, 0x0000001c, 0x00000069, 
    0xffff0300, 0x00000002, 0x0000001c, 0x00000000, 0x00000062, 0x00000044, 
    0x00020003, 0x00010000, 0x0000004c, 0x00000000, 0x0000005c, 0x00020002, 
    0x00010000, 0x0000004c, 0x00000000, 0x63786164, 0x6400abab, 0x00010003, 
    0x00010004, 0x00010000, 0x00000000, 0x63786d75, 0x6c007073, 0x5f335f30, 
    0x00322e30, 0x2e373737, 0x362e3000, 0x00000000, 0x00000048, 0x10000100, 
    0x00000000, 0x00000000, 0x00002042, 0x00000003, 0x00000001, 0x0000f0a0, 
    0x0000f1a1, 0x00000000, 0x4001c400, 0x22000000, 0xc80f0000, 0x00000000, 
    0x8b000203, 0xc8080000, 0x001b1b00, 0xe1000100, 0xc8070000, 0x001bc000, 
    0xe1000000, 0xc80f8000, 0x00000000, 0xe2000000, 0x00000000, 0x00000000, 
    0x00000000
};
