#if 0
//
// Generated by 2.0.7776.0
//
//   fxc /T ps_1_1 /E PS_AcTextTexture scaleform.hlsl /Fh
//    PS_AcTextTexture.hlsl.h
//
//
// Parameters:
//
//   float4 color;
//   sampler2D tex0;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   color        c0       1
//   tex0         s0       1
//

// Shader type: pixel 

xps_3_0
defconst color, float, vector, [1, 4], c0
defconst tex0, sampler2d, object, [1, 1], s0
config AutoSerialize=false
config AutoResource=false
config PsMaxReg=1
// PsExportColorCount=1
// PsSampleControl=centers

dcl_texcoord r0.xy


    exec
    tfetch2D r0.w___, r0.xy, tf0
    alloc colors
    exece
    muls r0.y, c0.zw
    mul r1.z, r0.y, r0.x
  + mulsc r1.w, c0.w, r0.x
    mul r1.xy, r1.w, c0.xy
    mov oC0, r1

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xps_PS_AcTextTexture[] =
{
    0x102a1100, 0x000000d4, 0x00000060, 0x00000000, 0x00000024, 0x00000000, 
    0x000000b0, 0x00000000, 0x00000000, 0x00000088, 0x0000001c, 0x0000007b, 
    0xffff0300, 0x00000002, 0x0000001c, 0x00000000, 0x00000074, 0x00000044, 
    0x00020000, 0x00010000, 0x0000004c, 0x00000000, 0x0000005c, 0x00030000, 
    0x00010000, 0x00000064, 0x00000000, 0x636f6c6f, 0x7200abab, 0x00010003, 
    0x00010004, 0x00010000, 0x00000000, 0x74657830, 0x00ababab, 0x0004000c, 
    0x00010001, 0x00010000, 0x00000000, 0x70735f33, 0x5f300032, 0x2e302e37, 
    0x3737362e, 0x3000abab, 0x00000000, 0x00000060, 0x10000100, 0x00000004, 
    0x00000000, 0x00000821, 0x00010001, 0x00000001, 0x00003050, 0x00011002, 
    0x00001200, 0xc4000000, 0x00004003, 0x00002200, 0x00000000, 0x10080001, 
    0x1f1ffffb, 0x00004000, 0x08200000, 0x000000cb, 0xc2000000, 0xa8840101, 
    0x00b16c00, 0xc1000000, 0xc8030001, 0x001bb000, 0xa1010000, 0xc80f8000, 
    0x00000000, 0xe2010100, 0x00000000, 0x00000000, 0x00000000
};
