#if 0
//
// Generated by 2.0.7776.0
//
//   fxc /T ps_1_1 /E PS_CxformGauraudMultiplyTexture scaleform.hlsl /Fh
//    PS_CxformGauraudMultiplyTexture.hlsl.h
//
//
// Parameters:
//
//   float4 cxadd;
//   float4 cxmul;
//   sampler2D tex0;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   cxmul        c2       1
//   cxadd        c3       1
//   tex0         s0       1
//

// Shader type: pixel 

xps_3_0
defconst cxadd, float, vector, [1, 4], c3
defconst cxmul, float, vector, [1, 4], c2
defconst tex0, sampler2d, object, [1, 1], s0
config AutoSerialize=false
config AutoResource=false
config PsMaxReg=3
// PsExportColorCount=1
// PsSampleControl=both

dcl_texcoord r0.xy
dcl_color_centroid r1
dcl_color1_centroid r2

def c252, 0, 0, 0, 0
def c253, 0, 0, 0, 0
def c254, 0, 0, 0, 0
def c255, 1, -1, 0, 0


    exec
    tfetch2D r3, r0.xy, tf0
    alloc colors
    exec
    add r0.xyz, c3.xyz, c255.y
    add r3, r3.wxyz, -r1.wxyz
    mad r1, r3, r2.z, r1.wxyz
    mad r0.xyz, r1.yzw, c2.xyz, r0.xyz
    mad r1.x, r1.x, c2.w, c3.w
    mul r1.y, r1.x, r2.w
    exece
    subsc r0.w, -c255.x, -r1.y
    mad oC0, r1.y, r0, c255.x

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xps_PS_CxformGauraudMultiplyTexture[] =
{
    0x102a1100, 0x0000011c, 0x000000d0, 0x00000000, 0x00000024, 0x000000c8, 
    0x000000f0, 0x00000000, 0x00000000, 0x000000a0, 0x0000001c, 0x00000093, 
    0xffff0300, 0x00000003, 0x0000001c, 0x00000000, 0x0000008c, 0x00000058, 
    0x00020003, 0x00010000, 0x00000060, 0x00000000, 0x00000070, 0x00020002, 
    0x00010000, 0x00000060, 0x00000000, 0x00000076, 0x00030000, 0x00010000, 
    0x0000007c, 0x00000000, 0x63786164, 0x6400abab, 0x00010003, 0x00010004, 
    0x00010000, 0x00000000, 0x63786d75, 0x6c007465, 0x783000ab, 0x0004000c, 
    0x00010001, 0x00010000, 0x00000000, 0x70735f33, 0x5f300032, 0x2e302e37, 
    0x3737362e, 0x3000abab, 0x00000000, 0x00000001, 0x00000000, 0x00000000, 
    0x00000014, 0x01fc0010, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 
    0x00000040, 0x00000090, 0x10000300, 0x00000008, 0x00000000, 0x00002863, 
    0x00010007, 0x00000001, 0x00003050, 0x0000f1a0, 0x0000f2a1, 0x00000000, 
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x3f800000, 
    0xbf800000, 0x00000000, 0x00000000, 0x00011002, 0x00001200, 0xc4000000, 
    0x00006003, 0x20091200, 0x22000000, 0x10083001, 0x1f1ff688, 0x00004000, 
    0xc8070100, 0x00c0b100, 0x2003ff00, 0xc80f0103, 0x02ffff00, 0xe0030100, 
    0xc80f0101, 0x0000c6ff, 0xeb030201, 0xc8070100, 0x0015c0c0, 0xab010200, 
    0xc8010101, 0x006c1b1b, 0x8b010203, 0xc8020101, 0x006c1b00, 0xe1010200, 
    0xbc800001, 0x01000041, 0xc20101ff, 0xc80f8000, 0x00b1006c, 0xcb0100ff, 
    0x00000000, 0x00000000, 0x00000000
};
