#if 0
//
// Generated by 2.0.7776.0
//
//   fxc /T ps_1_1 /E PS_SolidColor scaleform.hlsl /Fh PS_SolidColor.hlsl.h
//
//
// Parameters:
//
//   float4 color;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   color        c0       1
//

// Shader type: pixel 

xps_3_0
defconst color, float, vector, [1, 4], c0
config AutoSerialize=false
config AutoResource=false
// PsExportColorCount=1


    alloc colors
    exece
    mov oC0, c0

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xps_PS_SolidColor[] =
{
    0x102a1100, 0x000000a4, 0x00000024, 0x00000000, 0x00000024, 0x00000000, 
    0x00000084, 0x00000000, 0x00000000, 0x0000005c, 0x0000001c, 0x0000004f, 
    0xffff0300, 0x00000001, 0x0000001c, 0x00000000, 0x00000048, 0x00000030, 
    0x00020000, 0x00010000, 0x00000038, 0x00000000, 0x636f6c6f, 0x7200abab, 
    0x00010003, 0x00010004, 0x00010000, 0x00000000, 0x70735f33, 0x5f300032, 
    0x2e302e37, 0x3737362e, 0x3000abab, 0x00000000, 0x00000024, 0x10000000, 
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000001, 0x00000000, 
    0x1001c400, 0x22000000, 0xc80f8000, 0x00000000, 0x22000000, 0x00000000, 
    0x00000000, 0x00000000
};
