p4 edit *.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T vs_1_1 /E VShaderStrip scaleform.hlsl /Fh VShaderStrip.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T vs_1_1 /E VShaderGlyph scaleform.hlsl /Fh VShaderGlyph.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T vs_1_1 /E VShaderStripXY16iC32 scaleform.hlsl /Fh VShaderStripXY16iC32.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T vs_1_1 /E VShaderStripXY16iCF32 scaleform.hlsl /Fh VShaderStripXY16iCF32.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T vs_1_1 /E VShaderStripXY16iCF32_T2 scaleform.hlsl /Fh VShaderStripXY16iCF32_T2.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T vs_1_1 /E VShaderGlyphSzc scaleform.hlsl /Fh VShaderGlyphSzc.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T vs_1_1 /E VShaderStripXY16iC32Szc scaleform.hlsl /Fh VShaderStripXY16iC32Szc.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T vs_1_1 /E VShaderStripXY16iCF32Szc scaleform.hlsl /Fh VShaderStripXY16iCF32Szc.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T vs_1_1 /E VShaderStripXY16iCF32Szc_T2 scaleform.hlsl /Fh VShaderStripXY16iCF32Szc_T2.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T vs_1_1 /E VShaderStripXY32fCF32 scaleform.hlsl /Fh VShaderStripXY32fCF32.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T vs_1_1 /E VShaderStripXYUV32fCF32 scaleform.hlsl /Fh VShaderStripXYUV32fCF32.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T vs_1_1 /E VShaderStripXYUVUV32fCF32 scaleform.hlsl /Fh VShaderStripXYUVUV32fCF32.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_SolidColor scaleform.hlsl /Fh PS_SolidColor.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_CxformTexture scaleform.hlsl /Fh PS_CxformTexture.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_CxformTextureMultiply scaleform.hlsl /Fh PS_CxformTextureMultiply.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_TextTextureColor scaleform.hlsl /Fh PS_TextTextureColor.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_CxformGauraud scaleform.hlsl /Fh PS_CxformGauraud.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_CxformGauraudMultiply scaleform.hlsl /Fh PS_CxformGauraudMultiply.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_CxformGauraudNoAddAlpha scaleform.hlsl /Fh PS_CxformGauraudNoAddAlpha.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_CxformGauraudMultiplyNoAddAlpha scaleform.hlsl /Fh PS_CxformGauraudMultiplyNoAddAlpha.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_CxformGauraudTexture scaleform.hlsl /Fh PS_CxformGauraudTexture.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_CxformGauraudMultiplyTexture scaleform.hlsl /Fh PS_CxformGauraudMultiplyTexture.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_Cxform2Texture scaleform.hlsl /Fh PS_Cxform2Texture.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_CxformMultiply2Texture scaleform.hlsl /Fh PS_CxformMultiply2Texture.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_AcSolidColor scaleform.hlsl /Fh PS_AcSolidColor.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_AcCxformTexture scaleform.hlsl /Fh PS_AcCxformTexture.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_AcCxformTextureMultiply scaleform.hlsl /Fh PS_AcCxformTextureMultiply.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_AcTextTexture scaleform.hlsl /Fh PS_AcTextTexture.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_AcTextTextureColor scaleform.hlsl /Fh PS_AcTextTextureColor.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_AcCxformGauraud scaleform.hlsl /Fh PS_AcCxformGauraud.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_AcCxformGauraudMultiply scaleform.hlsl /Fh PS_AcCxformGauraudMultiply.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_AcCxformGauraudNoAddAlpha scaleform.hlsl /Fh PS_AcCxformGauraudNoAddAlpha.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_AcCxformGauraudMultiplyNoAddAlpha scaleform.hlsl /Fh PS_AcCxformGauraudMultiplyNoAddAlpha.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_AcCxformGauraudTexture scaleform.hlsl /Fh PS_AcCxformGauraudTexture.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_AcCxformGauraudMultiplyTexture scaleform.hlsl /Fh PS_AcCxformGauraudMultiplyTexture.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_AcCxform2Texture scaleform.hlsl /Fh PS_AcCxform2Texture.hlsl.h
"C:\Program Files\Microsoft Xbox 360 SDK\bin\win32\fxc.exe" /T ps_1_1 /E PS_AcCxformMultiply2Texture scaleform.hlsl /Fh PS_AcCxformMultiply2Texture.hlsl.h