#if 0
//
// Generated by 2.0.7776.0
//
//   fxc /T vs_1_1 /E VShaderStripXYUVUV32fCF32 scaleform.hlsl /Fh
//    VShaderStripXYUVUV32fCF32.hlsl.h
//
// Shader type: vertex 

xvs_3_0
config AutoSerialize=false
config AutoResource=false
config VsMaxReg=3
config VsResource=1
// VsExportCount=3

dcl_index r0.x
dcl_texcoord o0.xy
dcl_texcoord1 o1.xy
dcl_color o2
dcl_color1 o3


    exec
    vfetch r3, r0.x, position
    vfetch r2.__xy, r0.x, texcoord
    vfetch r2.xy__, r0.x, texcoord1
    vfetch r1, r0.x, color
    vfetch r0, r0.x, color1
    alloc position
    exec
    mov oPos, r3
    alloc interpolators
    exece
    mov o0.xy, r2.zw
    mov o1.xy, r2.xy
    mov o2, r1
    mov o3, r0

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xvs_VShaderStripXYUVUV32fCF32[] =
{
    0x102a1101, 0x000000b4, 0x000000a8, 0x00000000, 0x00000024, 0x00000000, 
    0x00000058, 0x00000000, 0x00000000, 0x00000030, 0x0000001c, 0x00000023, 
    0xfffe0300, 0x00000000, 0x00000000, 0x00000000, 0x0000001c, 0x76735f33, 
    0x5f300032, 0x2e302e37, 0x3737362e, 0x3000abab, 0x00000000, 0x000000a8, 
    0x00310003, 0x00000000, 0x00000000, 0x00003084, 0x00000001, 0x00000005, 
    0x00000004, 0x00000290, 0x00100003, 0x00005004, 0x00015005, 0x0000a006, 
    0x0031a007, 0x00003050, 0x00013151, 0x0002f2a0, 0x0003f3a1, 0x00001009, 
    0x0000100a, 0x0000100b, 0x0000100c, 0xf1555003, 0x00001201, 0xc2000000, 
    0x00001008, 0x00001200, 0xc4000000, 0x00004009, 0x00002200, 0x00000000, 
    0x05f83000, 0x00000688, 0x00000000, 0x05f82000, 0x0000023f, 0x00000000, 
    0x05f82000, 0x00000fc8, 0x00000000, 0x05f81000, 0x00000688, 0x00000000, 
    0x05f80000, 0x00000688, 0x00000000, 0xc80f803e, 0x00000000, 0xe2030300, 
    0xc8038000, 0x001a1a00, 0xe2020200, 0xc8038001, 0x00b0b000, 0xe2020200, 
    0xc80f8002, 0x00000000, 0xe2010100, 0xc80f8003, 0x00000000, 0xe2000000, 
    0x00000000, 0x00000000, 0x00000000
};
