#if 0
//
// Generated by 2.0.7776.0
//
//   fxc /T vs_1_1 /E VShaderGlyphSzc scaleform.hlsl /Fh VShaderGlyphSzc.hlsl.h
//
//
// Parameters:
//
//   float4 mvp[4];
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   mvp          c0       2
//

// Shader type: vertex 

xvs_3_0
defconst mvp[0], float, vector, [1, 4], c0
defconst mvp[1], float, vector, [1, 4], c1
defconst mvp[2], float, vector, [1, 4], cX
defconst mvp[3], float, vector, [1, 4], cX
config AutoSerialize=false
config AutoResource=false
config VsMaxReg=2
config VsResource=1
// VsExportCount=1

dcl_index r0.x
dcl_texcoord o0.xy
dcl_color o1


    exec
    vfetch r2, r0.x, position
    vfetch r1.xy__, r0.x, texcoord
    vfetch r0, r0.x, color
    alloc position
    exec
    dp4 oPos.x, r2.wzxy, c0.wzxy
  + movs oPos.z, r2.z
    dp4 oPos.y, r2.wzxy, c1.wzxy
  + movs oPos.w, r2.w
    alloc interpolators
    exece
    mov o0.xy, r1.xy
    mov o1, r0

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xvs_VShaderGlyphSzc[] =
{
    0x102a1101, 0x000000c4, 0x00000084, 0x00000000, 0x00000024, 0x00000000, 
    0x00000080, 0x00000000, 0x00000000, 0x00000058, 0x0000001c, 0x0000004b, 
    0xfffe0300, 0x00000001, 0x0000001c, 0x00000000, 0x00000044, 0x00000030, 
    0x00020000, 0x00020000, 0x00000034, 0x00000000, 0x6d767000, 0x00010003, 
    0x00010004, 0x00040000, 0x00000000, 0x76735f33, 0x5f300032, 0x2e302e37, 
    0x3737362e, 0x3000abab, 0x00000000, 0x00000084, 0x00110002, 0x00000000, 
    0x00000000, 0x00001842, 0x00000001, 0x00000003, 0x00000002, 0x00000290, 
    0x00100003, 0x00005004, 0x0030a005, 0x00003050, 0x0001f1a0, 0x00001008, 
    0x00001009, 0x70153003, 0x00001200, 0xc2000000, 0x00002006, 0x00001200, 
    0xc4000000, 0x00002008, 0x00002200, 0x00000000, 0x05f82000, 0x00000688, 
    0x00000000, 0x05f81000, 0x00000fc8, 0x00000000, 0x05f80000, 0x00000688, 
    0x00000000, 0x1441803e, 0x00a7a7c6, 0xaf020002, 0x1482803e, 0x00a7a71b, 
    0xaf020102, 0xc8038000, 0x00b0b000, 0xe2010100, 0xc80f8001, 0x00000000, 
    0xe2000000, 0x00000000, 0x00000000, 0x00000000
};
