#if 0
//
// Generated by 2.0.7776.0
//
//   fxc /T vs_1_1 /E VShaderStripXY16iCF32_T2 scaleform.hlsl /Fh
//    VShaderStripXY16iCF32_T2.hlsl.h
//
//
// Parameters:
//
//   float4 mvp[4];
//   float4 texgen[4];
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   mvp          c0       2
//   texgen       c4       4
//

// Shader type: vertex 

xvs_3_0
defconst mvp[0], float, vector, [1, 4], c0
defconst mvp[1], float, vector, [1, 4], c1
defconst mvp[2], float, vector, [1, 4], cX
defconst mvp[3], float, vector, [1, 4], cX
defconst texgen[0], float, vector, [1, 4], c4
defconst texgen[1], float, vector, [1, 4], c5
defconst texgen[2], float, vector, [1, 4], c6
defconst texgen[3], float, vector, [1, 4], c7
config AutoSerialize=false
config AutoResource=false
config VsMaxReg=2
config VsResource=1
// VsExportCount=3

dcl_index r0.x
dcl_texcoord o0.xy
dcl_texcoord1 o1.xy
dcl_color o2
dcl_color1 o3


    exec
    vfetch r1, r0.x, position
    vfetch r2, r0.x, color
    vfetch r0, r0.x, color1
    alloc position
    exec
    dp4 oPos.x, r1.wzxy, c0.wzxy
  + movs oPos.z, r1.z
    dp4 oPos.y, r1.wzxy, c1.wzxy
  + movs oPos.w, r1.w
    alloc interpolators
    exece
    mov o2, r2
    mov o3, r0
    dp4 o0.x, r1.wzxy, c4.wzxy
    dp4 o0.y, r1.wzxy, c5.wzxy
    dp4 o1.x, r1.wzxy, c6.wzxy
    dp4 o1.y, r1.wzxy, c7.wzxy

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xvs_VShaderStripXY16iCF32_T2[] =
{
    0x102a1101, 0x000000f8, 0x000000b4, 0x00000000, 0x00000024, 0x00000000, 
    0x0000009c, 0x00000000, 0x00000000, 0x00000074, 0x0000001c, 0x00000066, 
    0xfffe0300, 0x00000002, 0x0000001c, 0x00000000, 0x0000005f, 0x00000044, 
    0x00020000, 0x00020000, 0x00000048, 0x00000000, 0x00000058, 0x00020004, 
    0x00040000, 0x00000048, 0x00000000, 0x6d767000, 0x00010003, 0x00010004, 
    0x00040000, 0x00000000, 0x74657867, 0x656e0076, 0x735f335f, 0x3000322e, 
    0x302e3737, 0x37362e30, 0x00ababab, 0x00000000, 0x000000b4, 0x00310002, 
    0x00000000, 0x00000000, 0x00003084, 0x00000001, 0x00000003, 0x00000006, 
    0x00000290, 0x00100003, 0x0000a004, 0x0031a005, 0x00003050, 0x00023151, 
    0x0004f2a0, 0x0005f3a1, 0x0000000a, 0x0000100b, 0x0000000c, 0x0000100d, 
    0x00001008, 0x00001009, 0x70153003, 0x00001200, 0xc2000000, 0x00002006, 
    0x00001200, 0xc4000000, 0x00006008, 0x00002200, 0x00000000, 0x05f81000, 
    0x00000688, 0x00000000, 0x05f82000, 0x00000688, 0x00000000, 0x05f80000, 
    0x00000688, 0x00000000, 0x1441803e, 0x00a7a7c6, 0xaf010001, 0x1482803e, 
    0x00a7a71b, 0xaf010101, 0xc80f8002, 0x00000000, 0xe2020200, 0xc80f8003, 
    0x00000000, 0xe2000000, 0xc8018000, 0x00a7a700, 0xaf010400, 0xc8028000, 
    0x00a7a700, 0xaf010500, 0xc8018001, 0x00a7a700, 0xaf010600, 0xc8028001, 
    0x00a7a700, 0xaf010700, 0x00000000, 0x00000000, 0x00000000
};
