#if 0
//
// Generated by 2.0.7776.0
//
//   fxc /T vs_1_1 /E VShaderStrip scaleform.hlsl /Fh VShaderStrip.hlsl.h
//
//
// Parameters:
//
//   float4 mvp[4];
//   float4 texgen[4];
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   mvp          c0       2
//   texgen       c4       2
//

// Shader type: vertex 

xvs_3_0
defconst mvp[0], float, vector, [1, 4], c0
defconst mvp[1], float, vector, [1, 4], c1
defconst mvp[2], float, vector, [1, 4], cX
defconst mvp[3], float, vector, [1, 4], cX
defconst texgen[0], float, vector, [1, 4], c4
defconst texgen[1], float, vector, [1, 4], c5
defconst texgen[2], float, vector, [1, 4], cX
defconst texgen[3], float, vector, [1, 4], cX
config AutoSerialize=false
config AutoResource=false
config VsResource=1

dcl_index r0.x
dcl_texcoord o0.xy


    exec
    vfetch r0, r0.x, position
    alloc position
    exec
    dp4 oPos.x, r0.wzxy, c0.wzxy
  + movs oPos.z, r0.z
    dp4 oPos.y, r0.wzxy, c1.wzxy
  + movs oPos.w, r0.w
    alloc interpolators
    exece
    dp4 o0.x, r0.wzxy, c4.wzxy
    dp4 o0.y, r0.wzxy, c5.wzxy

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xvs_VShaderStrip[] =
{
    0x102a1101, 0x000000d4, 0x0000006c, 0x00000000, 0x00000024, 0x00000000, 
    0x0000009c, 0x00000000, 0x00000000, 0x00000074, 0x0000001c, 0x00000066, 
    0xfffe0300, 0x00000002, 0x0000001c, 0x00000000, 0x0000005f, 0x00000044, 
    0x00020000, 0x00020000, 0x00000048, 0x00000000, 0x00000058, 0x00020004, 
    0x00020000, 0x00000048, 0x00000000, 0x6d767000, 0x00010003, 0x00010004, 
    0x00040000, 0x00000000, 0x74657867, 0x656e0076, 0x735f335f, 0x3000322e, 
    0x302e3737, 0x37362e30, 0x00ababab, 0x00000000, 0x0000006c, 0x00010000, 
    0x00000000, 0x00000000, 0x00000821, 0x00000001, 0x00000001, 0x00000002, 
    0x00000290, 0x00000003, 0x00003050, 0x00000006, 0x00001007, 0x10011003, 
    0x00001200, 0xc2000000, 0x00002004, 0x00001200, 0xc4000000, 0x00002006, 
    0x00002200, 0x00000000, 0x05f80000, 0x00000688, 0x00000000, 0x1441803e, 
    0x00a7a7c6, 0xaf000000, 0x1482803e, 0x00a7a71b, 0xaf000100, 0xc8018000, 
    0x00a7a700, 0xaf000400, 0xc8028000, 0x00a7a700, 0xaf000500, 0x00000000, 
    0x00000000, 0x00000000
};
