// Stub for VinceEvents.h : The actual file is auto-generated by the
// specific application based on the EventSpecs.xml file. This stub
// is only included in the library files because it is referenced by Vince.h
