//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
//public partial class component
//{

//   private assetreference[] assetreferenceField;

//   private componentDecal[] decalField;

//   private componentAttach[] attachField;

//   /// <remarks/>
//   [System.Xml.Serialization.XmlElementAttribute("assetreference")]
//   public assetreference[] assetreference
//   {
//      get
//      {
//         return this.assetreferenceField;
//      }
//      set
//      {
//         this.assetreferenceField = value;
//      }
//   }

//   /// <remarks/>
//   [System.Xml.Serialization.XmlElementAttribute("decal", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
//   public componentDecal[] decal
//   {
//      get
//      {
//         return this.decalField;
//      }
//      set
//      {
//         this.decalField = value;
//      }
//   }

//   /// <remarks/>
//   [System.Xml.Serialization.XmlElementAttribute("attach", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
//   public componentAttach[] attach
//   {
//      get
//      {
//         return this.attachField;
//      }
//      set
//      {
//         this.attachField = value;
//      }
//   }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
//public partial class componentDecal
//{

//   private string effecttypeField;

//   private string selectedtextureField;

//   private string widthField;

//   private string heightField;

//   /// <remarks/>
//   [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
//   public string effecttype
//   {
//      get
//      {
//         return this.effecttypeField;
//      }
//      set
//      {
//         this.effecttypeField = value;
//      }
//   }

//   /// <remarks/>
//   [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
//   public string selectedtexture
//   {
//      get
//      {
//         return this.selectedtextureField;
//      }
//      set
//      {
//         this.selectedtextureField = value;
//      }
//   }

//   /// <remarks/>
//   [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
//   public string width
//   {
//      get
//      {
//         return this.widthField;
//      }
//      set
//      {
//         this.widthField = value;
//      }
//   }

//   /// <remarks/>
//   [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
//   public string height
//   {
//      get
//      {
//         return this.heightField;
//      }
//      set
//      {
//         this.heightField = value;
//      }
//   }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
//public partial class componentAttach
//{

//   private string aField;

//   private string fromboneField;

//   private string toboneField;

//   private string syncanimsField;

//   private string allowrotationField;

//   /// <remarks/>
//   [System.Xml.Serialization.XmlAttributeAttribute()]
//   public string a
//   {
//      get
//      {
//         return this.aField;
//      }
//      set
//      {
//         this.aField = value;
//      }
//   }

//   /// <remarks/>
//   [System.Xml.Serialization.XmlAttributeAttribute()]
//   public string frombone
//   {
//      get
//      {
//         return this.fromboneField;
//      }
//      set
//      {
//         this.fromboneField = value;
//      }
//   }

//   /// <remarks/>
//   [System.Xml.Serialization.XmlAttributeAttribute()]
//   public string tobone
//   {
//      get
//      {
//         return this.toboneField;
//      }
//      set
//      {
//         this.toboneField = value;
//      }
//   }

//   /// <remarks/>
//   [System.Xml.Serialization.XmlAttributeAttribute()]
//   public string syncanims
//   {
//      get
//      {
//         return this.syncanimsField;
//      }
//      set
//      {
//         this.syncanimsField = value;
//      }
//   }

//   /// <remarks/>
//   [System.Xml.Serialization.XmlAttributeAttribute()]
//   public string allowrotation
//   {
//      get
//      {
//         return this.allowrotationField;
//      }
//      set
//      {
//         this.allowrotationField = value;
//      }
//   }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
//public partial class assetreference
//{

//   private string fileField;

//   private assetreferenceTag[] tagField;

//   private string typeField;

//   /// <remarks/>
//   [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
//   public string file
//   {
//      get
//      {
//         return this.fileField;
//      }
//      set
//      {
//         this.fileField = value;
//      }
//   }

//   /// <remarks/>
//   [System.Xml.Serialization.XmlElementAttribute("tag", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
//   public assetreferenceTag[] tag
//   {
//      get
//      {
//         return this.tagField;
//      }
//      set
//      {
//         this.tagField = value;
//      }
//   }

//   /// <remarks/>
//   [System.Xml.Serialization.XmlAttributeAttribute()]
//   public string type
//   {
//      get
//      {
//         return this.typeField;
//      }
//      set
//      {
//         this.typeField = value;
//      }
//   }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
//public partial class assetreferenceTag
//{

//   private string typeField;

//   private string checkvisibleField;

//   private string setField;

//   private string valueField;

//   /// <remarks/>
//   [System.Xml.Serialization.XmlAttributeAttribute()]
//   public string type
//   {
//      get
//      {
//         return this.typeField;
//      }
//      set
//      {
//         this.typeField = value;
//      }
//   }

//   /// <remarks/>
//   [System.Xml.Serialization.XmlAttributeAttribute()]
//   public string checkvisible
//   {
//      get
//      {
//         return this.checkvisibleField;
//      }
//      set
//      {
//         this.checkvisibleField = value;
//      }
//   }

//   /// <remarks/>
//   [System.Xml.Serialization.XmlAttributeAttribute()]
//   public string set
//   {
//      get
//      {
//         return this.setField;
//      }
//      set
//      {
//         this.setField = value;
//      }
//   }

//   /// <remarks/>
//   [System.Xml.Serialization.XmlTextAttribute()]
//   public string Value
//   {
//      get
//      {
//         return this.valueField;
//      }
//      set
//      {
//         this.valueField = value;
//      }
//   }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
//public partial class anim
//{

//   private string componentField;

//   private assetreference[] assetreferenceField;

//   /// <remarks/>
//   [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
//   public string component
//   {
//      get
//      {
//         return this.componentField;
//      }
//      set
//      {
//         this.componentField = value;
//      }
//   }

//   /// <remarks/>
//   [System.Xml.Serialization.XmlElementAttribute("assetreference")]
//   public assetreference[] assetreference
//   {
//      get
//      {
//         return this.assetreferenceField;
//      }
//      set
//      {
//         this.assetreferenceField = value;
//      }
//   }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
//public partial class animfile
//{

//   private string defineboneField;

//   private animfileAttachment[] attachmentField;

//   private component[] componentField;

//   private anim[] animField;

//   /// <remarks/>
//   [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
//   public string definebone
//   {
//      get
//      {
//         return this.defineboneField;
//      }
//      set
//      {
//         this.defineboneField = value;
//      }
//   }

//   /// <remarks/>
//   [System.Xml.Serialization.XmlElementAttribute("attachment", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
//   public animfileAttachment[] attachment
//   {
//      get
//      {
//         return this.attachmentField;
//      }
//      set
//      {
//         this.attachmentField = value;
//      }
//   }

//   /// <remarks/>
//   [System.Xml.Serialization.XmlElementAttribute("component")]
//   public component[] component
//   {
//      get
//      {
//         return this.componentField;
//      }
//      set
//      {
//         this.componentField = value;
//      }
//   }

//   /// <remarks/>
//   [System.Xml.Serialization.XmlElementAttribute("anim")]
//   public anim[] anim
//   {
//      get
//      {
//         return this.animField;
//      }
//      set
//      {
//         this.animField = value;
//      }
//   }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
//public partial class animfileAttachment
//{

//   private component[] componentField;

//   private anim[] animField;

//   /// <remarks/>
//   [System.Xml.Serialization.XmlElementAttribute("component")]
//   public component[] component
//   {
//      get
//      {
//         return this.componentField;
//      }
//      set
//      {
//         this.componentField = value;
//      }
//   }

//   /// <remarks/>
//   [System.Xml.Serialization.XmlElementAttribute("anim")]
//   public anim[] anim
//   {
//      get
//      {
//         return this.animField;
//      }
//      set
//      {
//         this.animField = value;
//      }
//   }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
//public partial class NewDataSet
//{

//   private object[] itemsField;

//   /// <remarks/>
//   [System.Xml.Serialization.XmlElementAttribute("anim", typeof(anim))]
//   [System.Xml.Serialization.XmlElementAttribute("Visual", typeof(animfile))]
//   [System.Xml.Serialization.XmlElementAttribute("assetreference", typeof(assetreference))]
//   [System.Xml.Serialization.XmlElementAttribute("component", typeof(component))]
//   public object[] Items
//   {
//      get
//      {
//         return this.itemsField;
//      }
//      set
//      {
//         this.itemsField = value;
//      }
//   }
//}
