#if 0
//
// Generated by 2.0.7776.0
//
//   fxc /T ps_2_0 /E PSFixedFunc fixedFuncShaders.hlsl /Fh
//    fixedFuncPSWhite.hlsl.h /Vn g_xps_WhitePS
//
// Shader type: pixel 

xps_3_0
config AutoSerialize=false
config AutoResource=false
// PsExportColorCount=1

def c252, 0, 0, 0, 0
def c253, 0, 0, 0, 0
def c254, 0, 0, 0, 0
def c255, 1, 0, 0, 0


    alloc colors
    exece
    movs oC0.x111, c255.x

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xps_WhitePS[] =
{
    0x102a1100, 0x000000a0, 0x00000064, 0x00000000, 0x00000024, 0x00000058, 
    0x00000080, 0x00000000, 0x00000000, 0x00000030, 0x0000001c, 0x00000023, 
    0xffff0300, 0x00000000, 0x00000000, 0x00000000, 0x0000001c, 0x70735f33, 
    0x5f300032, 0x2e302e37, 0x3737362e, 0x3000abab, 0x00000000, 0x00000001, 
    0x00000000, 0x00000000, 0x00000014, 0x01fc0010, 0x00000000, 0x00000000, 
    0x00000000, 0x00000000, 0x00000040, 0x00000024, 0x10000000, 0x00000000, 
    0x00000000, 0x00000000, 0x00000000, 0x00000001, 0x00000000, 0x00000000, 
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x3f800000, 0x00000000, 
    0x00000000, 0x00000000, 0x00000000, 0x1001c400, 0x22000000, 0x14fec000, 
    0x0000006c, 0xc20000ff, 0x00000000, 0x00000000, 0x00000000
};
