#if 0
//
// Generated by 2.0.7776.0
//
//   fxc /T ps_2_0 /E PSFixedFunc /D DIFFUSE fixedFuncShaders.hlsl /Fh
//    fixedFuncPSDiffuse.hlsl.h /Vn g_xps_DiffusePS
//
// Shader type: pixel 

xps_3_0
config AutoSerialize=false
config AutoResource=false
// PsExportColorCount=1

dcl_color_centroid r0


    alloc colors
    exece
    mov oC0, r0

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xps_DiffusePS[] =
{
    0x102a1100, 0x0000007c, 0x00000024, 0x00000000, 0x00000024, 0x00000000, 
    0x00000058, 0x00000000, 0x00000000, 0x00000030, 0x0000001c, 0x00000023, 
    0xffff0300, 0x00000000, 0x00000000, 0x00000000, 0x0000001c, 0x70735f33, 
    0x5f300032, 0x2e302e37, 0x3737362e, 0x3000abab, 0x00000000, 0x00000024, 
    0x10000000, 0x00000000, 0x00000000, 0x00001021, 0x00000001, 0x00000001, 
    0x0000f0a0, 0x00000000, 0x1001c400, 0x22000000, 0xc80f8000, 0x00000000, 
    0xe2000000, 0x00000000, 0x00000000, 0x00000000
};
