#if 0
//
// Generated by 2.0.7776.0
//
//   fxc /T ps_2_0 /E PSFixedFunc /D DIFFUSE /D UV0 /D UV1
//    fixedFuncShaders.hlsl /Fh fixedFuncPSDiffuseTex2.hlsl.h /Vn
//    g_xps_DiffuseTex2PS
//
//
// Parameters:
//
//   sampler2D gSampler0;
//   sampler2D gSampler1;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   gSampler0    s0       1
//   gSampler1    s1       1
//

// Shader type: pixel 

xps_3_0
defconst gSampler0, sampler2d, object, [1, 1], s0
defconst gSampler1, sampler2d, object, [1, 1], s1
config AutoSerialize=false
config AutoResource=false
config PsMaxReg=2
// PsExportColorCount=1
// PsSampleControl=both

dcl_texcoord r0.xy
dcl_texcoord1 r1.xy
dcl_color_centroid r2


    exec
    tfetch2D r1, r1.xy, tf1
    tfetch2D r0, r0.xy, tf0
    alloc colors
    exece
    mul r2, r0, r2
    mul oC0, r2, r1

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xps_DiffuseTex2PS[] =
{
    0x102a1100, 0x000000d0, 0x00000054, 0x00000000, 0x00000024, 0x00000000, 
    0x000000a4, 0x00000000, 0x00000000, 0x0000007c, 0x0000001c, 0x00000071, 
    0xffff0300, 0x00000002, 0x0000001c, 0x00000000, 0x0000006a, 0x00000044, 
    0x00030000, 0x00010000, 0x00000050, 0x00000000, 0x00000060, 0x00030001, 
    0x00010000, 0x00000050, 0x00000000, 0x6753616d, 0x706c6572, 0x3000abab, 
    0x0004000c, 0x00010001, 0x00010000, 0x00000000, 0x6753616d, 0x706c6572, 
    0x31007073, 0x5f335f30, 0x00322e30, 0x2e373737, 0x362e3000, 0x00000000, 
    0x00000054, 0x10000200, 0x00000008, 0x00000000, 0x00002063, 0x00030007, 
    0x00000001, 0x00003050, 0x00003151, 0x0000f2a0, 0x00052002, 0x00001200, 
    0xc4000000, 0x00002004, 0x00002200, 0x00000000, 0x10181021, 0x1f1ff688, 
    0x00004000, 0x10080001, 0x1f1ff688, 0x00004000, 0xc80f0202, 0x00000000, 
    0xe1000200, 0xc80f8000, 0x00000000, 0xe1020100, 0x00000000, 0x00000000, 
    0x00000000
};
