#if 0
//
// Generated by 2.0.7776.0
//
//   fxc /T ps_2_0 /E PSDepthVis fixedFuncShaders.hlsl /Fh
//    fixedFuncPSDepthVis.hlsl.h /Vn g_xps_DepthVisPS
//
//
// Parameters:
//
//   float4 gAdd;
//   float4 gMul;
//   sampler2D gSamplerVis;
//   float gSlice;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   gMul         c0       1
//   gAdd         c1       1
//   gSlice       c2       1
//   gSamplerVis  s0       1
//

// Shader type: pixel 

xps_3_0
defconst gAdd, float, vector, [1, 4], c1
defconst gMul, float, vector, [1, 4], c0
defconst gSamplerVis, sampler2d, object, [1, 1], s0
defconst gSlice, float, scalar, [1, 1], c2
config AutoSerialize=false
config AutoResource=false
// PsExportColorCount=1
// PsSampleControl=centers

dcl_texcoord r0.xy


    exec
    movs r0.z, c2.x
    tfetch3D r0.x___, r0.xyz, tf0
    alloc colors
    exece
    mad oC0, r0.x, c0, c1

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xps_DepthVisPS[] =
{
    0x102a1100, 0x00000120, 0x00000048, 0x00000000, 0x00000024, 0x00000000, 
    0x000000fc, 0x00000000, 0x00000000, 0x000000d4, 0x0000001c, 0x000000c7, 
    0xffff0300, 0x00000004, 0x0000001c, 0x00000000, 0x000000c0, 0x0000006c, 
    0x00020001, 0x00010000, 0x00000074, 0x00000000, 0x00000084, 0x00020000, 
    0x00010000, 0x00000074, 0x00000000, 0x00000089, 0x00030000, 0x00010000, 
    0x00000098, 0x00000000, 0x000000a8, 0x00020002, 0x00010000, 0x000000b0, 
    0x00000000, 0x67416464, 0x00ababab, 0x00010003, 0x00010004, 0x00010000, 
    0x00000000, 0x674d756c, 0x00675361, 0x6d706c65, 0x72566973, 0x00ababab, 
    0x0004000c, 0x00010001, 0x00010000, 0x00000000, 0x67536c69, 0x636500ab, 
    0x00000003, 0x00010001, 0x00010000, 0x00000000, 0x70735f33, 0x5f300032, 
    0x2e302e37, 0x3737362e, 0x3000abab, 0x00000000, 0x00000048, 0x10000000, 
    0x00000004, 0x00000000, 0x00000821, 0x00010001, 0x00000001, 0x00003050, 
    0x00042002, 0x00001200, 0xc4000000, 0x00001004, 0x00002200, 0x00000000, 
    0x14400000, 0x0000006c, 0xc2000002, 0x90080001, 0x1f1ffff8, 0x00008000, 
    0xc80f8000, 0x006c0000, 0x8b000001, 0x00000000, 0x00000000, 0x00000000
};
