#if 0
//
// Generated by 2.0.7776.0
//
//   fxc /T vs_2_0 /E VSFixedFunc fixedFuncShaders.hlsl /Fh
//    fixedFuncVSPos.hlsl.h /Vn g_xvs_PosVS
//
//
// Parameters:
//
//   float4x4 gWorldViewProjMatrix;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   gWorldViewProjMatrix c0       4
//

// Shader type: vertex 

xvs_3_0
defconst gWorldViewProjMatrix, float, matrix_columns, [4, 4], c0-3
config AutoSerialize=false
config AutoResource=false
config VsResource=1

dcl_index r0.x


    exec
    vfetch r0, r0.x, position
    alloc position
    exec
    dp4 oPos.x, r0.wzxy, c0.wzxy
    dp4 oPos.y, r0.wzxy, c1.wzxy
    dp4 oPos.z, r0.wzxy, c2.wzxy
    dp4 oPos.w, r0.wzxy, c3.wzxy
    alloc interpolators
    exece

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xvs_PosVS[] =
{
    0x102a1101, 0x000000c0, 0x0000006c, 0x00000000, 0x00000024, 0x00000000, 
    0x00000094, 0x00000000, 0x00000000, 0x0000006c, 0x0000001c, 0x0000005f, 
    0xfffe0300, 0x00000001, 0x0000001c, 0x00000000, 0x00000058, 0x00000030, 
    0x00020000, 0x00040000, 0x00000048, 0x00000000, 0x67576f72, 0x6c645669, 
    0x65775072, 0x6f6a4d61, 0x74726978, 0x00ababab, 0x00030003, 0x00040004, 
    0x00010000, 0x00000000, 0x76735f33, 0x5f300032, 0x2e302e37, 0x3737362e, 
    0x3000abab, 0x00000000, 0x0000006c, 0x00010000, 0x00000000, 0x00000000, 
    0x00000000, 0x00000001, 0x00000001, 0x00000000, 0x00000290, 0x00000003, 
    0x10011003, 0x00001200, 0xc2000000, 0x00004004, 0x00001200, 0xc4000000, 
    0x00000003, 0x00002200, 0x00000000, 0x05f80000, 0x00000688, 0x00000000, 
    0xc801803e, 0x00a7a700, 0xaf000000, 0xc802803e, 0x00a7a700, 0xaf000100, 
    0xc804803e, 0x00a7a700, 0xaf000200, 0xc808803e, 0x00a7a700, 0xaf000300, 
    0x00000000, 0x00000000, 0x00000000
};
