/* 
 * 
 * Confidential Information of Telekinesys Research Limited (t/a Havok).  Not for disclosure or distribution without Havok's
 * prior written consent.This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Level 2 and Level 3 source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2007 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 * 
 */

// Autogenerated by genRegister.py

HK_CLASS(hkBaseObject)
HK_CLASS(hkReferencedObject)
HK_STRUCT(hkAabb)
HK_STRUCT(hkAabbUint32)
HK_STRUCT(hkBitField)
HK_STRUCT(hkClass)
HK_STRUCT(hkClassEnum)
HK_STRUCT(hkClassEnumItem)
HK_STRUCT(hkClassMember)
HK_STRUCT(hkContactPoint)
HK_STRUCT(hkContactPointMaterial)
HK_STRUCT(hkCustomAttributes)
HK_STRUCT(hkCustomAttributesAttribute)
HK_STRUCT(hkMonitorStreamFrameInfo)
HK_STRUCT(hkMonitorStreamStringMap)
HK_STRUCT(hkMonitorStreamStringMapStringMap)
HK_STRUCT(hkMotionState)
HK_STRUCT(hkMultiThreadCheck)
HK_STRUCT(hkRangeInt32Attribute)
HK_STRUCT(hkRangeRealAttribute)
HK_STRUCT(hkSphere)
HK_STRUCT(hkSweptTransform)

/*
* Havok SDK - PUBLIC RELEASE, BUILD(#20070919)
*
* Confidential Information of Havok.  (C) Copyright 1999-2007 
* Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
* Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
* rights, and intellectual property rights in the Havok software remain in
* Havok and/or its suppliers.
*
* Use of this software for evaluation purposes is subject to and indicates 
* acceptance of the End User licence Agreement for this product. A copy of 
* the license is included with this software and is also available from salesteam@havok.com.
*
*/
