////////////////////////////////////////////////////////////////////
//
// haloWarsLocalizedProject.spa.h
//
// Auto-generated on Friday, 12 December 2008 at 11:51:32
// XLAST project version 1.0.170.0
// SPA Compiler version 2.0.7776.0
//
////////////////////////////////////////////////////////////////////

#ifndef __HALO_WARS_SPA_H__
#define __HALO_WARS_SPA_H__

#ifdef __cplusplus
extern "C" {
#endif

//
// Title info
//

#define TITLEID_HALO_WARS                           0x4D530808

//
// Context ids
//
// These values are passed as the dwContextId to XUserSetContext.
//

#define CONTEXT_PRE_CON_GAMESIZE                    0
#define CONTEXT_PRE_CON_ACTION                      1
#define CONTEXT_PRE_CON_MOVIENAME                   2
#define CONTEXT_PRE_CON_DIFFICULTY                  3
#define CONTEXT_PRE_CON_HWGAMEMODE                  4
#define CONTEXT_PRE_CON_NETWORK                     5
#define CONTEXT_PRE_CON_GAMERESULT                  6

//
// Context values
//
// These values are passed as the dwContextValue to XUserSetContext.
//

// Values for CONTEXT_PRE_CON_GAMESIZE

#define CONTEXT_PRE_CON_GAMESIZE_PRE_CON_GAMESIZE_SOLO 0
#define CONTEXT_PRE_CON_GAMESIZE_PRE_CON_GAMESIZE_WITHFRIEND 1
#define CONTEXT_PRE_CON_GAMESIZE_PRE_CON_GAMESIZE_1V1 2
#define CONTEXT_PRE_CON_GAMESIZE_PRE_CON_GAMESIZE_2V2 3
#define CONTEXT_PRE_CON_GAMESIZE_PRE_CON_GAMESIZE_3V3 4

// Values for CONTEXT_PRE_CON_ACTION

#define CONTEXT_PRE_CON_ACTION_PRE_CON_ACTION_WAITING 0
#define CONTEXT_PRE_CON_ACTION_PRE_CON_ACTION_INLOBBY 1
#define CONTEXT_PRE_CON_ACTION_PRE_CON_ACTION_SEARCHING 2
#define CONTEXT_PRE_CON_ACTION_PRE_CON_ACTION_INGAME 3
#define CONTEXT_PRE_CON_ACTION_PRE_CON_ACTION_POSTGAME 4
#define CONTEXT_PRE_CON_ACTION_PRE_CON_ACTION_ASLEEP 5

// Values for CONTEXT_PRE_CON_MOVIENAME

#define CONTEXT_PRE_CON_MOVIENAME_PRE_CON_MOVIENAME_UNKNOWN 0
#define CONTEXT_PRE_CON_MOVIENAME_PRE_CON_MOVIENAME_LOGOS 1
#define CONTEXT_PRE_CON_MOVIENAME_PRE_CON_MOVIENAME_CREDITS 2
#define CONTEXT_PRE_CON_MOVIENAME_PRE_CON_MOVIENAME_C01 3
#define CONTEXT_PRE_CON_MOVIENAME_PRE_CON_MOVIENAME_C03 4
#define CONTEXT_PRE_CON_MOVIENAME_PRE_CON_MOVIENAME_C04 5
#define CONTEXT_PRE_CON_MOVIENAME_PRE_CON_MOVIENAME_C05 6
#define CONTEXT_PRE_CON_MOVIENAME_PRE_CON_MOVIENAME_C06 7
#define CONTEXT_PRE_CON_MOVIENAME_PRE_CON_MOVIENAME_C07 8
#define CONTEXT_PRE_CON_MOVIENAME_PRE_CON_MOVIENAME_C08 9
#define CONTEXT_PRE_CON_MOVIENAME_PRE_CON_MOVIENAME_C09 10
#define CONTEXT_PRE_CON_MOVIENAME_PRE_CON_MOVIENAME_C09B 11
#define CONTEXT_PRE_CON_MOVIENAME_PRE_CON_MOVIENAME_C10 12
#define CONTEXT_PRE_CON_MOVIENAME_PRE_CON_MOVIENAME_C11 13
#define CONTEXT_PRE_CON_MOVIENAME_PRE_CON_MOVIENAME_C12 14
#define CONTEXT_PRE_CON_MOVIENAME_PRE_CON_MOVIENAME_C13 15
#define CONTEXT_PRE_CON_MOVIENAME_PRE_CON_MOVIENAME_C14 16
#define CONTEXT_PRE_CON_MOVIENAME_PRE_CON_MOVIENAME_C15 17

// Values for CONTEXT_PRE_CON_DIFFICULTY

#define CONTEXT_PRE_CON_DIFFICULTY_PRE_CON_DIFF_EASY 0
#define CONTEXT_PRE_CON_DIFFICULTY_PRE_CON_DIFF_NORMAL 1
#define CONTEXT_PRE_CON_DIFFICULTY_PRE_CON_DIFF_HEROIC 2
#define CONTEXT_PRE_CON_DIFFICULTY_PRE_CON_DIFF_LEGENDARY 3

// Values for CONTEXT_PRE_CON_HWGAMEMODE

#define CONTEXT_PRE_CON_HWGAMEMODE_MODESTANDARD     0
#define CONTEXT_PRE_CON_HWGAMEMODE_MODEDEATHMATCH   1

// Values for CONTEXT_PRE_CON_NETWORK

#define CONTEXT_PRE_CON_NETWORK_LIVE                0
#define CONTEXT_PRE_CON_NETWORK_LOCAL               1

// Values for CONTEXT_PRE_CON_GAMERESULT

#define CONTEXT_PRE_CON_GAMERESULT_WON              0
#define CONTEXT_PRE_CON_GAMERESULT_LOST             1
#define CONTEXT_PRE_CON_GAMERESULT_TIED             2

// Values for X_CONTEXT_PRESENCE

#define CONTEXT_PRESENCE_PRE_MODE_MAINMENU          0
#define CONTEXT_PRESENCE_PRE_MODE_CAMPAIGNCOOPPLAY  1
#define CONTEXT_PRESENCE_PRE_MODE_CAMPAIGNLOBBY     2
#define CONTEXT_PRESENCE_PRE_MODE_CAMPAIGNPOSTLOBBY 3
#define CONTEXT_PRESENCE_PRE_MODE_CAMPAIGNSOLOPLAY  4
#define CONTEXT_PRESENCE_PRE_MODE_LEADERBOARDS      5
#define CONTEXT_PRESENCE_PRE_MODE_PLAYINGSKIRM      6
#define CONTEXT_PRESENCE_PRE_MODE_SERVICERECORD     7
#define CONTEXT_PRESENCE_PRE_MODE_SKIRMLIVELOBBY    8
#define CONTEXT_PRESENCE_PRE_MODE_SKIRMLOCALLOBBY   9
#define CONTEXT_PRESENCE_PRE_MODE_SKIRMMATCHMAKING  10
#define CONTEXT_PRESENCE_PRE_MODE_SKIRMPOSTLOBBY    11
#define CONTEXT_PRESENCE_PRE_MODE_TIMELINE          12
#define CONTEXT_PRESENCE_PRE_MODE_WATCHINGMOVIE     13

// Values for X_CONTEXT_GAME_MODE

#define CONTEXT_GAME_MODE_PARTYHOPPER               0
#define CONTEXT_GAME_MODE_STANDARD_1V1              1
#define CONTEXT_GAME_MODE_STANDARD_2V2              2
#define CONTEXT_GAME_MODE_TEAM_2V2                  3
#define CONTEXT_GAME_MODE_STANDARD_3V3              4
#define CONTEXT_GAME_MODE_TEAM_3V3                  5
#define CONTEXT_GAME_MODE_DM_1V1                    6
#define CONTEXT_GAME_MODE_DM_2V2                    7
#define CONTEXT_GAME_MODE_DM_TEAM_2V2               8
#define CONTEXT_GAME_MODE_DM_3V3                    9
#define CONTEXT_GAME_MODE_DM_TEAM_3V3               10
#define CONTEXT_GAME_MODE_RANDOM_1V1                11
#define CONTEXT_GAME_MODE_RANDOM_2V2                12
#define CONTEXT_GAME_MODE_RANDOM_TEAM_2V2           13
#define CONTEXT_GAME_MODE_RANDOM_3V3                14
#define CONTEXT_GAME_MODE_RANDOM_TEAM_3V3           15

//
// Property ids
//
// These values are passed as the dwPropertyId value to XUserSetProperty
// and as the dwPropertyId value in the XUSER_PROPERTY structure.
//

#define PROPERTY_GAMEWASCOOP                        0x1000000C
#define PROPERTY_MISSIONINDEX                       0x1000000D
#define PROPERTY_LOBBYMAXPLAYERS                    0x1000000E
#define PROPERTY_LOBBYCURRENTPLAYERS                0x1000000F
#define PROPERTY_GAMETIMEMINUTES                    0x10000010
#define PROPERTY_GAMESPLAYED                        0x20000008
#define PROPERTY_GAMEWINS                           0x20000009
#define PROPERTY_GAMESCORE                          0x2000000A
#define PROPERTY_GAMETOTALSCORE                     0x2000000B

//
// Achievement ids
//
// These values are used in the dwAchievementId member of the
// XUSER_ACHIEVEMENT structure that is used with
// XUserWriteAchievements and XUserCreateAchievementEnumerator.
//

#define ACHIEVEMENT_ACH_MEET_SERGEANT_FORGE         7
#define ACHIEVEMENT_ACH_ICE_WARRIORS                8
#define ACHIEVEMENT_ACH_KEY_TO_PIRTH                9
#define ACHIEVEMENT_ACH_UGLY_IS_ONLY_SKIN_DEEP      11
#define ACHIEVEMENT_ACH_NO_WAY_HOME                 12
#define ACHIEVEMENT_ACH_ADJUDICATE_THE_ARBITER      13
#define ACHIEVEMENT_ACH_DETOUR_THE_GREAT_JOURNEY    14
#define ACHIEVEMENT_ACH_MOMMAS_BOY                  15
#define ACHIEVEMENT_ACH_CRUSHED_COLORS              16
#define ACHIEVEMENT_ACH_MR_PUNCTUAL                 17
#define ACHIEVEMENT_ACH_OWN_WORST_ENEMY             18
#define ACHIEVEMENT_ACH_WALL_OF_RECOGNITION         19
#define ACHIEVEMENT_ACH_EPIC_GRINDER                20
#define ACHIEVEMENT_ACH_EVERYTHINGS_BETTER_WITH_BACON 21
#define ACHIEVEMENT_ACH_ENDLESS_FUN                 22
#define ACHIEVEMENT_ACH_COVENANT_HOT_DROP           23
#define ACHIEVEMENT_ACH_THE_REAL_WINNER             25
#define ACHIEVEMENT_ACH_HES_GOT_THE_JACK            26
#define ACHIEVEMENT_ACH_RHINO_HUGGER                27
#define ACHIEVEMENT_ACH_MICRO_MANAGER               28
#define ACHIEVEMENT_ACH_RAMBLIN_MAN                 29
#define ACHIEVEMENT_ACH_SWEET_NAPTIME               30
#define ACHIEVEMENT_ACH_THE_PROCRASTINATOR          31
#define ACHIEVEMENT_ACH_BATTENED_DOWN_THE_HATCHES   32
#define ACHIEVEMENT_ACH_HANDY_WITH_TOOLS            33
#define ACHIEVEMENT_ACH_BEAMING_WITH_PRIDE          34
#define ACHIEVEMENT_ACH_DIDNT_GET_TO_SECOND_BASE    35
#define ACHIEVEMENT_ACH_THINKIN_ABOUT_MY_DOORBELL   36
#define ACHIEVEMENT_ACH_BACKSCRATCHER               37
#define ACHIEVEMENT_ACH_OMG_BFF_FTW                 38
#define ACHIEVEMENT_ACH_PLAYIN_THE_FIELD            39
#define ACHIEVEMENT_ACH_GALLIVANT_AROUND_THE_GALAXY 40
#define ACHIEVEMENT_ACH_EMPIRE_BUILDER              41
#define ACHIEVEMENT_ACH_TITAN                       42
#define ACHIEVEMENT_ACH_BIG_ALS_SCOOTER             43
#define ACHIEVEMENT_ACH_MY_VIRTUAL_FRIENDS_LOVE_ME  44
#define ACHIEVEMENT_ACH_WALK_OFF_WINNER             45
#define ACHIEVEMENT_ACH_2_BUGS_ARE_BETTER_THAN_1    46
#define ACHIEVEMENT_ACH_PENNY_PINCHER               47
#define ACHIEVEMENT_ACH_N00B_N0_M0R3                48
#define ACHIEVEMENT_ACH_SO_LONELY_AT_THE_TOP        49
#define ACHIEVEMENT_ACH_BASICALLY_NAIVE             50
#define ACHIEVEMENT_ACH_OFFICER_ON_DECK             51
#define ACHIEVEMENT_ACH_RUNNING_THE_SHOW            52
#define ACHIEVEMENT_ACH_ALAS_POOR_ANDREW_THOMAS     53
#define ACHIEVEMENT_ACH_GRAVEROBBER                 54
#define ACHIEVEMENT_ACH_HALO_ACADEMIC               55
#define ACHIEVEMENT_ACH_HALO_HISTORIAN              56
#define ACHIEVEMENT_ACH_READY_FOR_THE_SEQUEL        57
#define ACHIEVEMENT_ACH_24_HOURS_OF_QUALITY         58

//
// Stats view ids
//
// These are used in the dwViewId member of the XUSER_STATS_SPEC structure
// passed to the XUserReadStats* and XUserCreateStatsEnumerator* functions.
//

// Skill leaderboards for ranked game modes

#define STATS_VIEW_SKILL_RANKED_PARTYHOPPER         0xFFFF0000
#define STATS_VIEW_SKILL_RANKED_STANDARD_1V1        0xFFFF0001
#define STATS_VIEW_SKILL_RANKED_STANDARD_2V2        0xFFFF0002
#define STATS_VIEW_SKILL_RANKED_TEAM_2V2            0xFFFF0003
#define STATS_VIEW_SKILL_RANKED_STANDARD_3V3        0xFFFF0004
#define STATS_VIEW_SKILL_RANKED_TEAM_3V3            0xFFFF0005
#define STATS_VIEW_SKILL_RANKED_DM_1V1              0xFFFF0006
#define STATS_VIEW_SKILL_RANKED_DM_2V2              0xFFFF0007
#define STATS_VIEW_SKILL_RANKED_DM_TEAM_2V2         0xFFFF0008
#define STATS_VIEW_SKILL_RANKED_DM_3V3              0xFFFF0009
#define STATS_VIEW_SKILL_RANKED_DM_TEAM_3V3         0xFFFF000A
#define STATS_VIEW_SKILL_RANKED_RANDOM_1V1          0xFFFF000B
#define STATS_VIEW_SKILL_RANKED_RANDOM_2V2          0xFFFF000C
#define STATS_VIEW_SKILL_RANKED_RANDOM_TEAM_2V2     0xFFFF000D
#define STATS_VIEW_SKILL_RANKED_RANDOM_3V3          0xFFFF000E
#define STATS_VIEW_SKILL_RANKED_RANDOM_TEAM_3V3     0xFFFF000F

// Skill leaderboards for unranked (standard) game modes

#define STATS_VIEW_SKILL_STANDARD_PARTYHOPPER       0xFFFE0000
#define STATS_VIEW_SKILL_STANDARD_STANDARD_1V1      0xFFFE0001
#define STATS_VIEW_SKILL_STANDARD_STANDARD_2V2      0xFFFE0002
#define STATS_VIEW_SKILL_STANDARD_TEAM_2V2          0xFFFE0003
#define STATS_VIEW_SKILL_STANDARD_STANDARD_3V3      0xFFFE0004
#define STATS_VIEW_SKILL_STANDARD_TEAM_3V3          0xFFFE0005
#define STATS_VIEW_SKILL_STANDARD_DM_1V1            0xFFFE0006
#define STATS_VIEW_SKILL_STANDARD_DM_2V2            0xFFFE0007
#define STATS_VIEW_SKILL_STANDARD_DM_TEAM_2V2       0xFFFE0008
#define STATS_VIEW_SKILL_STANDARD_DM_3V3            0xFFFE0009
#define STATS_VIEW_SKILL_STANDARD_DM_TEAM_3V3       0xFFFE000A
#define STATS_VIEW_SKILL_STANDARD_RANDOM_1V1        0xFFFE000B
#define STATS_VIEW_SKILL_STANDARD_RANDOM_2V2        0xFFFE000C
#define STATS_VIEW_SKILL_STANDARD_RANDOM_TEAM_2V2   0xFFFE000D
#define STATS_VIEW_SKILL_STANDARD_RANDOM_3V3        0xFFFE000E
#define STATS_VIEW_SKILL_STANDARD_RANDOM_TEAM_3V3   0xFFFE000F

// Title defined leaderboards

#define STATS_VIEW_MPWINSLIFETIME_1V1_GT1           1
#define STATS_VIEW_MPWINSLIFETIME_2V2_GT1           2
#define STATS_VIEW_MPWINSLIFETIME_2V2T_GT1          3
#define STATS_VIEW_MPWINSLIFETIME_3V3_GT1           4
#define STATS_VIEW_MPWINSLIFETIME_3V3T_GT1          5
#define STATS_VIEW_MPWINSLIFETIME_1V1_GT2           6
#define STATS_VIEW_MPWINSLIFETIME_2V2_GT2           7
#define STATS_VIEW_MPWINSLIFETIME_2V2T_GT2          8
#define STATS_VIEW_MPWINSLIFETIME_3V3_GT2           9
#define STATS_VIEW_MPWINSLIFETIME_3V3T_GT2          10
#define STATS_VIEW_MPWINSLIFETIME_1V1_GT3           11
#define STATS_VIEW_MPWINSLIFETIME_2V2_GT3           12
#define STATS_VIEW_MPWINSLIFETIME_2V2T_GT3          13
#define STATS_VIEW_MPWINSLIFETIME_3V3_GT3           14
#define STATS_VIEW_MPWINSLIFETIME_3V3T_GT3          15
#define STATS_VIEW_MPWINSLIFETIME_1V1_GT4           16
#define STATS_VIEW_MPWINSLIFETIME_2V2_GT4           17
#define STATS_VIEW_MPWINSLIFETIME_2V2T_GT4          18
#define STATS_VIEW_MPWINSLIFETIME_3V3_GT4           19
#define STATS_VIEW_MPWINSLIFETIME_3V3T_GT4          20
#define STATS_VIEW_MPWINSLIFETIME_1V1_GT5           21
#define STATS_VIEW_MPWINSLIFETIME_2V2_GT5           22
#define STATS_VIEW_MPWINSLIFETIME_2V2T_GT5          23
#define STATS_VIEW_MPWINSLIFETIME_3V3_GT5           24
#define STATS_VIEW_MPWINSLIFETIME_3V3T_GT5          25
#define STATS_VIEW_MPWINSLIFETIME_1V1_GT6           26
#define STATS_VIEW_MPWINSLIFETIME_2V2_GT6           27
#define STATS_VIEW_MPWINSLIFETIME_2V2T_GT6          28
#define STATS_VIEW_MPWINSLIFETIME_3V3_GT6           29
#define STATS_VIEW_MPWINSLIFETIME_3V3T_GT6          30
#define STATS_VIEW_MPWINSMONTHLY_1V1_GT1            31
#define STATS_VIEW_MPWINSMONTHLY_2V2_GT1            32
#define STATS_VIEW_MPWINSMONTHLY_2V2T_GT1           33
#define STATS_VIEW_MPWINSMONTHLY_3V3_GT1            34
#define STATS_VIEW_MPWINSMONTHLY_3V3T_GT1           35
#define STATS_VIEW_MPWINSMONTHLY_1V1_GT2            36
#define STATS_VIEW_MPWINSMONTHLY_2V2_GT2            37
#define STATS_VIEW_MPWINSMONTHLY_2V2T_GT2           38
#define STATS_VIEW_MPWINSMONTHLY_3V3_GT2            39
#define STATS_VIEW_MPWINSMONTHLY_3V3T_GT2           40
#define STATS_VIEW_MPWINSMONTHLY_1V1_GT3            41
#define STATS_VIEW_MPWINSMONTHLY_2V2_GT3            42
#define STATS_VIEW_MPWINSMONTHLY_2V2T_GT3           43
#define STATS_VIEW_MPWINSMONTHLY_3V3_GT3            44
#define STATS_VIEW_MPWINSMONTHLY_3V3T_GT3           45
#define STATS_VIEW_MPWINSMONTHLY_1V1_GT4            46
#define STATS_VIEW_MPWINSMONTHLY_2V2_GT4            47
#define STATS_VIEW_MPWINSMONTHLY_2V2T_GT4           48
#define STATS_VIEW_MPWINSMONTHLY_3V3_GT4            49
#define STATS_VIEW_MPWINSMONTHLY_3V3T_GT4           50
#define STATS_VIEW_MPWINSMONTHLY_1V1_GT5            51
#define STATS_VIEW_MPWINSMONTHLY_2V2_GT5            52
#define STATS_VIEW_MPWINSMONTHLY_2V2T_GT5           53
#define STATS_VIEW_MPWINSMONTHLY_3V3_GT5            54
#define STATS_VIEW_MPWINSMONTHLY_3V3T_GT5           55
#define STATS_VIEW_MPWINSMONTHLY_1V1_GT6            56
#define STATS_VIEW_MPWINSMONTHLY_2V2_GT6            57
#define STATS_VIEW_MPWINSMONTHLY_2V2T_GT6           58
#define STATS_VIEW_MPWINSMONTHLY_3V3_GT6            59
#define STATS_VIEW_MPWINSMONTHLY_3V3T_GT6           60
#define STATS_VIEW_MPWINSMONTHLY_L1_GT1             61
#define STATS_VIEW_MPWINSMONTHLY_L2_GT1             62
#define STATS_VIEW_MPWINSMONTHLY_L3_GT1             63
#define STATS_VIEW_MPWINSMONTHLY_L4_GT1             64
#define STATS_VIEW_MPWINSMONTHLY_L5_GT1             65
#define STATS_VIEW_MPWINSMONTHLY_L6_GT1             66
#define STATS_VIEW_MPWINSMONTHLY_L7_GT1             67
#define STATS_VIEW_MPWINSMONTHLY_L8_GT1             68
#define STATS_VIEW_MPWINSMONTHLY_L9_GT1             69
#define STATS_VIEW_MPWINSMONTHLY_L0_GT1             70
#define STATS_VIEW_MPWINSMONTHLY_L1_GT2             71
#define STATS_VIEW_MPWINSMONTHLY_L2_GT2             72
#define STATS_VIEW_MPWINSMONTHLY_L3_GT2             73
#define STATS_VIEW_MPWINSMONTHLY_L4_GT2             74
#define STATS_VIEW_MPWINSMONTHLY_L5_GT2             75
#define STATS_VIEW_MPWINSMONTHLY_L6_GT2             76
#define STATS_VIEW_MPWINSMONTHLY_L7_GT2             77
#define STATS_VIEW_MPWINSMONTHLY_L8_GT2             78
#define STATS_VIEW_MPWINSMONTHLY_L9_GT2             79
#define STATS_VIEW_MPWINSMONTHLY_L0_GT2             80
#define STATS_VIEW_MPWINSMONTHLY_L1_GT3             81
#define STATS_VIEW_MPWINSMONTHLY_L2_GT3             82
#define STATS_VIEW_MPWINSMONTHLY_L3_GT3             83
#define STATS_VIEW_MPWINSMONTHLY_L4_GT3             84
#define STATS_VIEW_MPWINSMONTHLY_L5_GT3             85
#define STATS_VIEW_MPWINSMONTHLY_L6_GT3             86
#define STATS_VIEW_MPWINSMONTHLY_L7_GT3             87
#define STATS_VIEW_MPWINSMONTHLY_L8_GT3             88
#define STATS_VIEW_MPWINSMONTHLY_L9_GT3             89
#define STATS_VIEW_MPWINSMONTHLY_L0_GT3             90
#define STATS_VIEW_MPWINSMONTHLY_L1_GT4             91
#define STATS_VIEW_MPWINSMONTHLY_L2_GT4             92
#define STATS_VIEW_MPWINSMONTHLY_L3_GT4             93
#define STATS_VIEW_MPWINSMONTHLY_L4_GT4             94
#define STATS_VIEW_MPWINSMONTHLY_L5_GT4             95
#define STATS_VIEW_MPWINSMONTHLY_L6_GT4             96
#define STATS_VIEW_MPWINSMONTHLY_L7_GT4             97
#define STATS_VIEW_MPWINSMONTHLY_L8_GT4             98
#define STATS_VIEW_MPWINSMONTHLY_L9_GT4             99
#define STATS_VIEW_MPWINSMONTHLY_L0_GT4             100
#define STATS_VIEW_MPWINSMONTHLY_L1_GT5             101
#define STATS_VIEW_MPWINSMONTHLY_L2_GT5             102
#define STATS_VIEW_MPWINSMONTHLY_L3_GT5             103
#define STATS_VIEW_MPWINSMONTHLY_L4_GT5             104
#define STATS_VIEW_MPWINSMONTHLY_L5_GT5             105
#define STATS_VIEW_MPWINSMONTHLY_L6_GT5             106
#define STATS_VIEW_MPWINSMONTHLY_L7_GT5             107
#define STATS_VIEW_MPWINSMONTHLY_L8_GT5             108
#define STATS_VIEW_MPWINSMONTHLY_L9_GT5             109
#define STATS_VIEW_MPWINSMONTHLY_L0_GT5             110
#define STATS_VIEW_MPWINSMONTHLY_L1_GT6             111
#define STATS_VIEW_MPWINSMONTHLY_L2_GT6             112
#define STATS_VIEW_MPWINSMONTHLY_L3_GT6             113
#define STATS_VIEW_MPWINSMONTHLY_L4_GT6             114
#define STATS_VIEW_MPWINSMONTHLY_L5_GT6             115
#define STATS_VIEW_MPWINSMONTHLY_L6_GT6             116
#define STATS_VIEW_MPWINSMONTHLY_L7_GT6             117
#define STATS_VIEW_MPWINSMONTHLY_L8_GT6             118
#define STATS_VIEW_MPWINSMONTHLY_L9_GT6             119
#define STATS_VIEW_MPWINSMONTHLY_L0_GT6             120
#define STATS_VIEW_CAMPSCORELIFETIME_SOLO           121
#define STATS_VIEW_CAMPSCORELIFETIME_COOP           122
#define STATS_VIEW_CAMPSCOREBYMISSION_M01_D1        123
#define STATS_VIEW_CAMPSCOREBYMISSION_M02_D1        124
#define STATS_VIEW_CAMPSCOREBYMISSION_M03_D1        125
#define STATS_VIEW_CAMPSCOREBYMISSION_M04_D1        126
#define STATS_VIEW_CAMPSCOREBYMISSION_M05_D1        127
#define STATS_VIEW_CAMPSCOREBYMISSION_M06_D1        128
#define STATS_VIEW_CAMPSCOREBYMISSION_M07_D1        129
#define STATS_VIEW_CAMPSCOREBYMISSION_M08_D1        130
#define STATS_VIEW_CAMPSCOREBYMISSION_M09_D1        131
#define STATS_VIEW_CAMPSCOREBYMISSION_M10_D1        132
#define STATS_VIEW_CAMPSCOREBYMISSION_M11_D1        133
#define STATS_VIEW_CAMPSCOREBYMISSION_M12_D1        134
#define STATS_VIEW_CAMPSCOREBYMISSION_M13_D1        135
#define STATS_VIEW_CAMPSCOREBYMISSION_M14_D1        136
#define STATS_VIEW_CAMPSCOREBYMISSION_M15_D1        137
#define STATS_VIEW_CAMPSCOREBYMISSION_M01_D2        138
#define STATS_VIEW_CAMPSCOREBYMISSION_M02_D2        139
#define STATS_VIEW_CAMPSCOREBYMISSION_M03_D2        140
#define STATS_VIEW_CAMPSCOREBYMISSION_M04_D2        141
#define STATS_VIEW_CAMPSCOREBYMISSION_M05_D2        142
#define STATS_VIEW_CAMPSCOREBYMISSION_M06_D2        143
#define STATS_VIEW_CAMPSCOREBYMISSION_M07_D2        144
#define STATS_VIEW_CAMPSCOREBYMISSION_M08_D2        145
#define STATS_VIEW_CAMPSCOREBYMISSION_M09_D2        146
#define STATS_VIEW_CAMPSCOREBYMISSION_M10_D2        147
#define STATS_VIEW_CAMPSCOREBYMISSION_M11_D2        148
#define STATS_VIEW_CAMPSCOREBYMISSION_M12_D2        149
#define STATS_VIEW_CAMPSCOREBYMISSION_M13_D2        150
#define STATS_VIEW_CAMPSCOREBYMISSION_M14_D2        151
#define STATS_VIEW_CAMPSCOREBYMISSION_M15_D2        152
#define STATS_VIEW_CAMPSCOREBYMISSION_M01_D3        153
#define STATS_VIEW_CAMPSCOREBYMISSION_M02_D3        154
#define STATS_VIEW_CAMPSCOREBYMISSION_M03_D3        155
#define STATS_VIEW_CAMPSCOREBYMISSION_M04_D3        156
#define STATS_VIEW_CAMPSCOREBYMISSION_M05_D3        157
#define STATS_VIEW_CAMPSCOREBYMISSION_M06_D3        158
#define STATS_VIEW_CAMPSCOREBYMISSION_M07_D3        159
#define STATS_VIEW_CAMPSCOREBYMISSION_M08_D3        160
#define STATS_VIEW_CAMPSCOREBYMISSION_M09_D3        161
#define STATS_VIEW_CAMPSCOREBYMISSION_M10_D3        162
#define STATS_VIEW_CAMPSCOREBYMISSION_M11_D3        163
#define STATS_VIEW_CAMPSCOREBYMISSION_M12_D3        164
#define STATS_VIEW_CAMPSCOREBYMISSION_M13_D3        165
#define STATS_VIEW_CAMPSCOREBYMISSION_M14_D3        166
#define STATS_VIEW_CAMPSCOREBYMISSION_M15_D3        167
#define STATS_VIEW_CAMPSCOREBYMISSION_M01_D4        168
#define STATS_VIEW_CAMPSCOREBYMISSION_M02_D4        169
#define STATS_VIEW_CAMPSCOREBYMISSION_M03_D4        170
#define STATS_VIEW_CAMPSCOREBYMISSION_M04_D4        171
#define STATS_VIEW_CAMPSCOREBYMISSION_M05_D4        172
#define STATS_VIEW_CAMPSCOREBYMISSION_M06_D4        173
#define STATS_VIEW_CAMPSCOREBYMISSION_M07_D4        174
#define STATS_VIEW_CAMPSCOREBYMISSION_M08_D4        175
#define STATS_VIEW_CAMPSCOREBYMISSION_M09_D4        176
#define STATS_VIEW_CAMPSCOREBYMISSION_M10_D4        177
#define STATS_VIEW_CAMPSCOREBYMISSION_M11_D4        178
#define STATS_VIEW_CAMPSCOREBYMISSION_M12_D4        179
#define STATS_VIEW_CAMPSCOREBYMISSION_M13_D4        180
#define STATS_VIEW_CAMPSCOREBYMISSION_M14_D4        181
#define STATS_VIEW_CAMPSCOREBYMISSION_M15_D4        182

//
// Stats view column ids
//
// These ids are used to read columns of stats views.  They are specified in
// the rgwColumnIds array of the XUSER_STATS_SPEC structure.  Rank, rating
// and gamertag are not retrieved as custom columns and so are not included
// in the following definitions.  They can be retrieved from each row's
// header (e.g., pStatsResults->pViews[x].pRows[y].dwRank, etc.).
//

// Column ids for MPWINSLIFETIME_1V1_GT1

#define STATS_COLUMN_MPWINSLIFETIME_1V1_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_1V1_GT1_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_2V2_GT1

#define STATS_COLUMN_MPWINSLIFETIME_2V2_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_2V2_GT1_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_2V2T_GT1

#define STATS_COLUMN_MPWINSLIFETIME_2V2T_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_2V2T_GT1_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_3V3_GT1

#define STATS_COLUMN_MPWINSLIFETIME_3V3_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_3V3_GT1_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_3V3T_GT1

#define STATS_COLUMN_MPWINSLIFETIME_3V3T_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_3V3T_GT1_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_1V1_GT2

#define STATS_COLUMN_MPWINSLIFETIME_1V1_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_1V1_GT2_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_2V2_GT2

#define STATS_COLUMN_MPWINSLIFETIME_2V2_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_2V2_GT2_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_2V2T_GT2

#define STATS_COLUMN_MPWINSLIFETIME_2V2T_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_2V2T_GT2_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_3V3_GT2

#define STATS_COLUMN_MPWINSLIFETIME_3V3_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_3V3_GT2_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_3V3T_GT2

#define STATS_COLUMN_MPWINSLIFETIME_3V3T_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_3V3T_GT2_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_1V1_GT3

#define STATS_COLUMN_MPWINSLIFETIME_1V1_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_1V1_GT3_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_2V2_GT3

#define STATS_COLUMN_MPWINSLIFETIME_2V2_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_2V2_GT3_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_2V2T_GT3

#define STATS_COLUMN_MPWINSLIFETIME_2V2T_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_2V2T_GT3_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_3V3_GT3

#define STATS_COLUMN_MPWINSLIFETIME_3V3_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_3V3_GT3_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_3V3T_GT3

#define STATS_COLUMN_MPWINSLIFETIME_3V3T_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_3V3T_GT3_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_1V1_GT4

#define STATS_COLUMN_MPWINSLIFETIME_1V1_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_1V1_GT4_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_2V2_GT4

#define STATS_COLUMN_MPWINSLIFETIME_2V2_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_2V2_GT4_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_2V2T_GT4

#define STATS_COLUMN_MPWINSLIFETIME_2V2T_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_2V2T_GT4_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_3V3_GT4

#define STATS_COLUMN_MPWINSLIFETIME_3V3_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_3V3_GT4_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_3V3T_GT4

#define STATS_COLUMN_MPWINSLIFETIME_3V3T_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_3V3T_GT4_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_1V1_GT5

#define STATS_COLUMN_MPWINSLIFETIME_1V1_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_1V1_GT5_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_2V2_GT5

#define STATS_COLUMN_MPWINSLIFETIME_2V2_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_2V2_GT5_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_2V2T_GT5

#define STATS_COLUMN_MPWINSLIFETIME_2V2T_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_2V2T_GT5_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_3V3_GT5

#define STATS_COLUMN_MPWINSLIFETIME_3V3_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_3V3_GT5_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_3V3T_GT5

#define STATS_COLUMN_MPWINSLIFETIME_3V3T_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_3V3T_GT5_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_1V1_GT6

#define STATS_COLUMN_MPWINSLIFETIME_1V1_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_1V1_GT6_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_2V2_GT6

#define STATS_COLUMN_MPWINSLIFETIME_2V2_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_2V2_GT6_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_2V2T_GT6

#define STATS_COLUMN_MPWINSLIFETIME_2V2T_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_2V2T_GT6_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_3V3_GT6

#define STATS_COLUMN_MPWINSLIFETIME_3V3_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_3V3_GT6_TOTALSCORE 1

// Column ids for MPWINSLIFETIME_3V3T_GT6

#define STATS_COLUMN_MPWINSLIFETIME_3V3T_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSLIFETIME_3V3T_GT6_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_1V1_GT1

#define STATS_COLUMN_MPWINSMONTHLY_1V1_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_1V1_GT1_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_2V2_GT1

#define STATS_COLUMN_MPWINSMONTHLY_2V2_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_2V2_GT1_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_2V2T_GT1

#define STATS_COLUMN_MPWINSMONTHLY_2V2T_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_2V2T_GT1_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_3V3_GT1

#define STATS_COLUMN_MPWINSMONTHLY_3V3_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_3V3_GT1_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_3V3T_GT1

#define STATS_COLUMN_MPWINSMONTHLY_3V3T_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_3V3T_GT1_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_1V1_GT2

#define STATS_COLUMN_MPWINSMONTHLY_1V1_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_1V1_GT2_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_2V2_GT2

#define STATS_COLUMN_MPWINSMONTHLY_2V2_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_2V2_GT2_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_2V2T_GT2

#define STATS_COLUMN_MPWINSMONTHLY_2V2T_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_2V2T_GT2_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_3V3_GT2

#define STATS_COLUMN_MPWINSMONTHLY_3V3_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_3V3_GT2_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_3V3T_GT2

#define STATS_COLUMN_MPWINSMONTHLY_3V3T_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_3V3T_GT2_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_1V1_GT3

#define STATS_COLUMN_MPWINSMONTHLY_1V1_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_1V1_GT3_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_2V2_GT3

#define STATS_COLUMN_MPWINSMONTHLY_2V2_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_2V2_GT3_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_2V2T_GT3

#define STATS_COLUMN_MPWINSMONTHLY_2V2T_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_2V2T_GT3_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_3V3_GT3

#define STATS_COLUMN_MPWINSMONTHLY_3V3_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_3V3_GT3_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_3V3T_GT3

#define STATS_COLUMN_MPWINSMONTHLY_3V3T_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_3V3T_GT3_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_1V1_GT4

#define STATS_COLUMN_MPWINSMONTHLY_1V1_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_1V1_GT4_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_2V2_GT4

#define STATS_COLUMN_MPWINSMONTHLY_2V2_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_2V2_GT4_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_2V2T_GT4

#define STATS_COLUMN_MPWINSMONTHLY_2V2T_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_2V2T_GT4_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_3V3_GT4

#define STATS_COLUMN_MPWINSMONTHLY_3V3_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_3V3_GT4_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_3V3T_GT4

#define STATS_COLUMN_MPWINSMONTHLY_3V3T_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_3V3T_GT4_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_1V1_GT5

#define STATS_COLUMN_MPWINSMONTHLY_1V1_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_1V1_GT5_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_2V2_GT5

#define STATS_COLUMN_MPWINSMONTHLY_2V2_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_2V2_GT5_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_2V2T_GT5

#define STATS_COLUMN_MPWINSMONTHLY_2V2T_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_2V2T_GT5_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_3V3_GT5

#define STATS_COLUMN_MPWINSMONTHLY_3V3_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_3V3_GT5_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_3V3T_GT5

#define STATS_COLUMN_MPWINSMONTHLY_3V3T_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_3V3T_GT5_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_1V1_GT6

#define STATS_COLUMN_MPWINSMONTHLY_1V1_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_1V1_GT6_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_2V2_GT6

#define STATS_COLUMN_MPWINSMONTHLY_2V2_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_2V2_GT6_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_2V2T_GT6

#define STATS_COLUMN_MPWINSMONTHLY_2V2T_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_2V2T_GT6_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_3V3_GT6

#define STATS_COLUMN_MPWINSMONTHLY_3V3_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_3V3_GT6_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_3V3T_GT6

#define STATS_COLUMN_MPWINSMONTHLY_3V3T_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_3V3T_GT6_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L1_GT1

#define STATS_COLUMN_MPWINSMONTHLY_L1_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L1_GT1_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L2_GT1

#define STATS_COLUMN_MPWINSMONTHLY_L2_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L2_GT1_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L3_GT1

#define STATS_COLUMN_MPWINSMONTHLY_L3_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L3_GT1_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L4_GT1

#define STATS_COLUMN_MPWINSMONTHLY_L4_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L4_GT1_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L5_GT1

#define STATS_COLUMN_MPWINSMONTHLY_L5_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L5_GT1_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L6_GT1

#define STATS_COLUMN_MPWINSMONTHLY_L6_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L6_GT1_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L7_GT1

#define STATS_COLUMN_MPWINSMONTHLY_L7_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L7_GT1_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L8_GT1

#define STATS_COLUMN_MPWINSMONTHLY_L8_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L8_GT1_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L9_GT1

#define STATS_COLUMN_MPWINSMONTHLY_L9_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L9_GT1_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L0_GT1

#define STATS_COLUMN_MPWINSMONTHLY_L0_GT1_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L0_GT1_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L1_GT2

#define STATS_COLUMN_MPWINSMONTHLY_L1_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L1_GT2_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L2_GT2

#define STATS_COLUMN_MPWINSMONTHLY_L2_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L2_GT2_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L3_GT2

#define STATS_COLUMN_MPWINSMONTHLY_L3_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L3_GT2_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L4_GT2

#define STATS_COLUMN_MPWINSMONTHLY_L4_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L4_GT2_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L5_GT2

#define STATS_COLUMN_MPWINSMONTHLY_L5_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L5_GT2_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L6_GT2

#define STATS_COLUMN_MPWINSMONTHLY_L6_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L6_GT2_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L7_GT2

#define STATS_COLUMN_MPWINSMONTHLY_L7_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L7_GT2_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L8_GT2

#define STATS_COLUMN_MPWINSMONTHLY_L8_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L8_GT2_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L9_GT2

#define STATS_COLUMN_MPWINSMONTHLY_L9_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L9_GT2_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L0_GT2

#define STATS_COLUMN_MPWINSMONTHLY_L0_GT2_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L0_GT2_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L1_GT3

#define STATS_COLUMN_MPWINSMONTHLY_L1_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L1_GT3_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L2_GT3

#define STATS_COLUMN_MPWINSMONTHLY_L2_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L2_GT3_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L3_GT3

#define STATS_COLUMN_MPWINSMONTHLY_L3_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L3_GT3_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L4_GT3

#define STATS_COLUMN_MPWINSMONTHLY_L4_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L4_GT3_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L5_GT3

#define STATS_COLUMN_MPWINSMONTHLY_L5_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L5_GT3_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L6_GT3

#define STATS_COLUMN_MPWINSMONTHLY_L6_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L6_GT3_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L7_GT3

#define STATS_COLUMN_MPWINSMONTHLY_L7_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L7_GT3_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L8_GT3

#define STATS_COLUMN_MPWINSMONTHLY_L8_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L8_GT3_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L9_GT3

#define STATS_COLUMN_MPWINSMONTHLY_L9_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L9_GT3_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L0_GT3

#define STATS_COLUMN_MPWINSMONTHLY_L0_GT3_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L0_GT3_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L1_GT4

#define STATS_COLUMN_MPWINSMONTHLY_L1_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L1_GT4_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L2_GT4

#define STATS_COLUMN_MPWINSMONTHLY_L2_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L2_GT4_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L3_GT4

#define STATS_COLUMN_MPWINSMONTHLY_L3_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L3_GT4_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L4_GT4

#define STATS_COLUMN_MPWINSMONTHLY_L4_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L4_GT4_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L5_GT4

#define STATS_COLUMN_MPWINSMONTHLY_L5_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L5_GT4_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L6_GT4

#define STATS_COLUMN_MPWINSMONTHLY_L6_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L6_GT4_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L7_GT4

#define STATS_COLUMN_MPWINSMONTHLY_L7_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L7_GT4_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L8_GT4

#define STATS_COLUMN_MPWINSMONTHLY_L8_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L8_GT4_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L9_GT4

#define STATS_COLUMN_MPWINSMONTHLY_L9_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L9_GT4_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L0_GT4

#define STATS_COLUMN_MPWINSMONTHLY_L0_GT4_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L0_GT4_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L1_GT5

#define STATS_COLUMN_MPWINSMONTHLY_L1_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L1_GT5_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L2_GT5

#define STATS_COLUMN_MPWINSMONTHLY_L2_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L2_GT5_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L3_GT5

#define STATS_COLUMN_MPWINSMONTHLY_L3_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L3_GT5_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L4_GT5

#define STATS_COLUMN_MPWINSMONTHLY_L4_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L4_GT5_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L5_GT5

#define STATS_COLUMN_MPWINSMONTHLY_L5_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L5_GT5_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L6_GT5

#define STATS_COLUMN_MPWINSMONTHLY_L6_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L6_GT5_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L7_GT5

#define STATS_COLUMN_MPWINSMONTHLY_L7_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L7_GT5_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L8_GT5

#define STATS_COLUMN_MPWINSMONTHLY_L8_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L8_GT5_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L9_GT5

#define STATS_COLUMN_MPWINSMONTHLY_L9_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L9_GT5_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L0_GT5

#define STATS_COLUMN_MPWINSMONTHLY_L0_GT5_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L0_GT5_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L1_GT6

#define STATS_COLUMN_MPWINSMONTHLY_L1_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L1_GT6_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L2_GT6

#define STATS_COLUMN_MPWINSMONTHLY_L2_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L2_GT6_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L3_GT6

#define STATS_COLUMN_MPWINSMONTHLY_L3_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L3_GT6_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L4_GT6

#define STATS_COLUMN_MPWINSMONTHLY_L4_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L4_GT6_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L5_GT6

#define STATS_COLUMN_MPWINSMONTHLY_L5_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L5_GT6_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L6_GT6

#define STATS_COLUMN_MPWINSMONTHLY_L6_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L6_GT6_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L7_GT6

#define STATS_COLUMN_MPWINSMONTHLY_L7_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L7_GT6_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L8_GT6

#define STATS_COLUMN_MPWINSMONTHLY_L8_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L8_GT6_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L9_GT6

#define STATS_COLUMN_MPWINSMONTHLY_L9_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L9_GT6_TOTALSCORE 1

// Column ids for MPWINSMONTHLY_L0_GT6

#define STATS_COLUMN_MPWINSMONTHLY_L0_GT6_GAMESPLAYED 2
#define STATS_COLUMN_MPWINSMONTHLY_L0_GT6_TOTALSCORE 1

// Column ids for CAMPSCORELIFETIME_SOLO

#define STATS_COLUMN_CAMPSCORELIFETIME_SOLO_GAMESPLAYED 1

// Column ids for CAMPSCORELIFETIME_COOP

#define STATS_COLUMN_CAMPSCORELIFETIME_COOP_GAMESPLAYED 1

// Column ids for CAMPSCOREBYMISSION_M01_D1

#define STATS_COLUMN_CAMPSCOREBYMISSION_M01_D1_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M02_D1

#define STATS_COLUMN_CAMPSCOREBYMISSION_M02_D1_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M03_D1

#define STATS_COLUMN_CAMPSCOREBYMISSION_M03_D1_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M04_D1

#define STATS_COLUMN_CAMPSCOREBYMISSION_M04_D1_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M05_D1

#define STATS_COLUMN_CAMPSCOREBYMISSION_M05_D1_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M06_D1

#define STATS_COLUMN_CAMPSCOREBYMISSION_M06_D1_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M07_D1

#define STATS_COLUMN_CAMPSCOREBYMISSION_M07_D1_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M08_D1

#define STATS_COLUMN_CAMPSCOREBYMISSION_M08_D1_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M09_D1

#define STATS_COLUMN_CAMPSCOREBYMISSION_M09_D1_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M10_D1

#define STATS_COLUMN_CAMPSCOREBYMISSION_M10_D1_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M11_D1

#define STATS_COLUMN_CAMPSCOREBYMISSION_M11_D1_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M12_D1

#define STATS_COLUMN_CAMPSCOREBYMISSION_M12_D1_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M13_D1

#define STATS_COLUMN_CAMPSCOREBYMISSION_M13_D1_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M14_D1

#define STATS_COLUMN_CAMPSCOREBYMISSION_M14_D1_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M15_D1

#define STATS_COLUMN_CAMPSCOREBYMISSION_M15_D1_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M01_D2

#define STATS_COLUMN_CAMPSCOREBYMISSION_M01_D2_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M02_D2

#define STATS_COLUMN_CAMPSCOREBYMISSION_M02_D2_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M03_D2

#define STATS_COLUMN_CAMPSCOREBYMISSION_M03_D2_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M04_D2

#define STATS_COLUMN_CAMPSCOREBYMISSION_M04_D2_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M05_D2

#define STATS_COLUMN_CAMPSCOREBYMISSION_M05_D2_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M06_D2

#define STATS_COLUMN_CAMPSCOREBYMISSION_M06_D2_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M07_D2

#define STATS_COLUMN_CAMPSCOREBYMISSION_M07_D2_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M08_D2

#define STATS_COLUMN_CAMPSCOREBYMISSION_M08_D2_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M09_D2

#define STATS_COLUMN_CAMPSCOREBYMISSION_M09_D2_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M10_D2

#define STATS_COLUMN_CAMPSCOREBYMISSION_M10_D2_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M11_D2

#define STATS_COLUMN_CAMPSCOREBYMISSION_M11_D2_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M12_D2

#define STATS_COLUMN_CAMPSCOREBYMISSION_M12_D2_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M13_D2

#define STATS_COLUMN_CAMPSCOREBYMISSION_M13_D2_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M14_D2

#define STATS_COLUMN_CAMPSCOREBYMISSION_M14_D2_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M15_D2

#define STATS_COLUMN_CAMPSCOREBYMISSION_M15_D2_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M01_D3

#define STATS_COLUMN_CAMPSCOREBYMISSION_M01_D3_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M02_D3

#define STATS_COLUMN_CAMPSCOREBYMISSION_M02_D3_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M03_D3

#define STATS_COLUMN_CAMPSCOREBYMISSION_M03_D3_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M04_D3

#define STATS_COLUMN_CAMPSCOREBYMISSION_M04_D3_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M05_D3

#define STATS_COLUMN_CAMPSCOREBYMISSION_M05_D3_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M06_D3

#define STATS_COLUMN_CAMPSCOREBYMISSION_M06_D3_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M07_D3

#define STATS_COLUMN_CAMPSCOREBYMISSION_M07_D3_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M08_D3

#define STATS_COLUMN_CAMPSCOREBYMISSION_M08_D3_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M09_D3

#define STATS_COLUMN_CAMPSCOREBYMISSION_M09_D3_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M10_D3

#define STATS_COLUMN_CAMPSCOREBYMISSION_M10_D3_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M11_D3

#define STATS_COLUMN_CAMPSCOREBYMISSION_M11_D3_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M12_D3

#define STATS_COLUMN_CAMPSCOREBYMISSION_M12_D3_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M13_D3

#define STATS_COLUMN_CAMPSCOREBYMISSION_M13_D3_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M14_D3

#define STATS_COLUMN_CAMPSCOREBYMISSION_M14_D3_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M15_D3

#define STATS_COLUMN_CAMPSCOREBYMISSION_M15_D3_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M01_D4

#define STATS_COLUMN_CAMPSCOREBYMISSION_M01_D4_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M02_D4

#define STATS_COLUMN_CAMPSCOREBYMISSION_M02_D4_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M03_D4

#define STATS_COLUMN_CAMPSCOREBYMISSION_M03_D4_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M04_D4

#define STATS_COLUMN_CAMPSCOREBYMISSION_M04_D4_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M05_D4

#define STATS_COLUMN_CAMPSCOREBYMISSION_M05_D4_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M06_D4

#define STATS_COLUMN_CAMPSCOREBYMISSION_M06_D4_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M07_D4

#define STATS_COLUMN_CAMPSCOREBYMISSION_M07_D4_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M08_D4

#define STATS_COLUMN_CAMPSCOREBYMISSION_M08_D4_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M09_D4

#define STATS_COLUMN_CAMPSCOREBYMISSION_M09_D4_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M10_D4

#define STATS_COLUMN_CAMPSCOREBYMISSION_M10_D4_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M11_D4

#define STATS_COLUMN_CAMPSCOREBYMISSION_M11_D4_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M12_D4

#define STATS_COLUMN_CAMPSCOREBYMISSION_M12_D4_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M13_D4

#define STATS_COLUMN_CAMPSCOREBYMISSION_M13_D4_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M14_D4

#define STATS_COLUMN_CAMPSCOREBYMISSION_M14_D4_WASCOOP 1

// Column ids for CAMPSCOREBYMISSION_M15_D4

#define STATS_COLUMN_CAMPSCOREBYMISSION_M15_D4_WASCOOP 1

//
// Matchmaking queries
//
// These values are passed as the dwProcedureIndex parameter to
// XSessionSearch to indicate which matchmaking query to run.
//

#define SESSION_MATCH_QUERY_BASETEST                0
#define SESSION_MATCH_QUERY_HOPPERSEARCH            3

//
// Gamer pictures
//
// These ids are passed as the dwPictureId parameter to XUserAwardGamerTile.
//

#define GAMER_PICTURE_GPIC_1_ANDERS                 51
#define GAMER_PICTURE_GPIC_2_FORGE                  52


#ifdef __cplusplus
}
#endif

#endif // __HALO_WARS_SPA_H__


